import type { RecipeIngredient } from './logic'

export interface SeedRecipe {
  /** Identificador fijo: sirve para que dos móviles no creen la misma receta dos veces. */
  slug: string
  title: string
  prep_minutes: number
  difficulty: 'facil' | 'media' | 'dificil'
  servings: number
  tags: string[]
  ingredients: RecipeIngredient[]
  steps: string[]
}

const i = (name: string, quantity: string, category: string): RecipeIngredient => ({ name, quantity, category })

/** Recetario inicial: cocina casera española, cantidades para 4 personas. */
export const SEED_RECIPES: SeedRecipe[] = [
  {
    slug: 'lentejas-con-chorizo',
    title: 'Lentejas estofadas con chorizo',
    prep_minutes: 60,
    difficulty: 'facil',
    servings: 4,
    tags: ['legumbres'],
    ingredients: [
      i('Lentejas pardinas', '350 g', 'despensa'),
      i('Chorizo', '1 (unos 150 g)', 'carne_pescado'),
      i('Patatas', '2 medianas', 'fruta_verdura'),
      i('Zanahorias', '2', 'fruta_verdura'),
      i('Cebolla', '1', 'fruta_verdura'),
      i('Pimiento verde', '1', 'fruta_verdura'),
      i('Ajo', '2 dientes', 'fruta_verdura'),
      i('Pimentón dulce', '1 cucharadita', 'despensa'),
      i('Hoja de laurel', '1', 'despensa'),
      i('Aceite de oliva', '3 cucharadas', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Lava las lentejas con agua fría y escúrrelas (las pardinas no necesitan remojo).',
      'Pica la cebolla, el pimiento y los ajos. Pela las zanahorias y córtalas en rodajas.',
      'En una olla con el aceite, sofríe la cebolla, el pimiento y el ajo a fuego medio unos 8 minutos.',
      'Añade el chorizo en rodajas y rehoga 2 minutos. Aparta la olla del fuego, echa el pimentón y remueve para que no se queme.',
      'Incorpora las lentejas, la zanahoria y el laurel. Cubre con agua (unos 1,5 litros) y lleva a ebullición.',
      'Baja el fuego y cuece tapado 25 minutos.',
      'Añade las patatas peladas y cortadas en trozos ("chascadas") y cuece 20 minutos más, hasta que estén tiernas.',
      'Prueba de sal, deja reposar 5 minutos y sirve.',
    ],
  },
  {
    slug: 'tortilla-de-patatas',
    title: 'Tortilla de patatas',
    prep_minutes: 40,
    difficulty: 'media',
    servings: 4,
    tags: [],
    ingredients: [
      i('Patatas', '700 g', 'fruta_verdura'),
      i('Huevos', '6', 'lacteos_huevos'),
      i('Cebolla', '1 (opcional)', 'fruta_verdura'),
      i('Aceite de oliva', 'abundante para freír', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Pela las patatas y córtalas en láminas finas. Pica la cebolla en juliana.',
      'Pon abundante aceite en una sartén a fuego medio y fríe las patatas con la cebolla y un poco de sal durante 20 minutos, hasta que estén blandas (no crujientes).',
      'Escurre bien el aceite (guárdalo para otra vez).',
      'Bate los huevos con una pizca de sal en un bol grande y mezcla con las patatas. Deja reposar 5 minutos.',
      'En una sartén con una cucharada de aceite bien caliente, echa la mezcla y cuaja 3 minutos a fuego medio.',
      'Dale la vuelta con ayuda de un plato y cuaja 2 minutos por el otro lado.',
      'Sirve templada.',
    ],
  },
  {
    slug: 'cocido-madrileno',
    title: 'Cocido madrileño',
    prep_minutes: 180,
    difficulty: 'media',
    servings: 4,
    tags: ['legumbres', 'carne'],
    ingredients: [
      i('Garbanzos', '300 g', 'despensa'),
      i('Morcillo de ternera', '400 g', 'carne_pescado'),
      i('Muslo de gallina o pollo', '2', 'carne_pescado'),
      i('Tocino', '100 g', 'carne_pescado'),
      i('Chorizo', '1', 'carne_pescado'),
      i('Morcilla', '1', 'carne_pescado'),
      i('Hueso de jamón', '1', 'carne_pescado'),
      i('Hueso de caña (tuétano)', '1', 'carne_pescado'),
      i('Patatas', '4', 'fruta_verdura'),
      i('Zanahorias', '2', 'fruta_verdura'),
      i('Repollo', '1/2', 'fruta_verdura'),
      i('Fideos finos', '100 g', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'La noche anterior, pon los garbanzos en remojo con agua templada y una pizca de sal.',
      'En una olla grande pon las carnes, el tocino y los huesos. Cubre con agua fría y lleva a ebullición, quitando la espuma que salga.',
      'Añade los garbanzos dentro de una malla y cuece a fuego suave unas 2 horas y media (o 40 minutos en olla exprés).',
      'Añade las zanahorias y las patatas peladas y cuece 30 minutos más.',
      'Aparte, cuece el repollo troceado con el chorizo y la morcilla unos 20 minutos.',
      'Cuela el caldo y cuece en él los fideos 4 minutos: es el primer vuelco (la sopa).',
      'Sirve después los garbanzos con las verduras y, por último, las carnes troceadas.',
    ],
  },
  {
    slug: 'garbanzos-con-espinacas',
    title: 'Garbanzos con espinacas',
    prep_minutes: 25,
    difficulty: 'facil',
    servings: 4,
    tags: ['legumbres', 'verdura', 'rapida'],
    ingredients: [
      i('Garbanzos cocidos', '2 botes (800 g)', 'despensa'),
      i('Espinacas frescas', '400 g', 'fruta_verdura'),
      i('Ajo', '3 dientes', 'fruta_verdura'),
      i('Pan', '2 rebanadas', 'panaderia'),
      i('Pimentón dulce', '1 cucharadita', 'despensa'),
      i('Comino molido', '1/2 cucharadita', 'despensa'),
      i('Vinagre', '1 cucharada', 'despensa'),
      i('Aceite de oliva', '4 cucharadas', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Enjuaga y escurre los garbanzos.',
      'En una sartén con el aceite, fríe los ajos laminados y el pan hasta que estén dorados. Sácalos y reserva.',
      'En el mismo aceite, saltea las espinacas hasta que se reduzcan (3–4 minutos).',
      'Machaca en un mortero el pan y los ajos fritos con el pimentón, el comino, el vinagre y un chorrito de agua.',
      'Añade a la sartén los garbanzos, el majado y un vaso de agua. Cuece 10 minutos a fuego suave.',
      'Prueba de sal y sirve.',
    ],
  },
  {
    slug: 'fabada-asturiana',
    title: 'Fabada asturiana',
    prep_minutes: 150,
    difficulty: 'media',
    servings: 4,
    tags: ['legumbres'],
    ingredients: [
      i('Fabes (alubias blancas grandes)', '400 g', 'despensa'),
      i('Chorizo asturiano', '2', 'carne_pescado'),
      i('Morcilla asturiana', '2', 'carne_pescado'),
      i('Panceta o lacón', '200 g', 'carne_pescado'),
      i('Azafrán', 'unas hebras', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'La noche anterior, pon las fabes en remojo en abundante agua fría. Aparte, pon la panceta o el lacón en remojo si están salados.',
      'Pon las fabes en una olla y cúbrelas con agua fría (2 dedos por encima). Lleva a ebullición.',
      'Añade el chorizo, la morcilla y la panceta. Cuando vuelva a hervir, retira la espuma.',
      'Cuece a fuego muy suave unas 2 horas. Cuando baje el agua, "asusta" las fabes con un chorrito de agua fría (unas 3 veces), sin remover: mueve la olla por las asas.',
      'A mitad de cocción añade el azafrán.',
      'Al final prueba de sal, deja reposar 15 minutos y sirve con el compango (las carnes) troceado.',
    ],
  },
  {
    slug: 'merluza-en-salsa-verde',
    title: 'Merluza en salsa verde',
    prep_minutes: 30,
    difficulty: 'facil',
    servings: 4,
    tags: ['pescado'],
    ingredients: [
      i('Merluza en rodajas o lomos', '800 g', 'carne_pescado'),
      i('Almejas', '250 g (opcional)', 'carne_pescado'),
      i('Ajo', '4 dientes', 'fruta_verdura'),
      i('Perejil fresco', '1 manojo', 'fruta_verdura'),
      i('Harina', '1 cucharada', 'despensa'),
      i('Vino blanco', '1/2 vaso', 'bebidas'),
      i('Caldo de pescado', '1 vaso', 'despensa'),
      i('Aceite de oliva', '5 cucharadas', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Si usas almejas, déjalas 30 minutos en agua con sal para que suelten la arena.',
      'Sala la merluza.',
      'En una cazuela amplia con el aceite, dora a fuego suave los ajos picados sin que se quemen.',
      'Añade la harina y remueve 1 minuto. Echa el vino y deja que se evapore el alcohol.',
      'Vierte el caldo poco a poco sin dejar de remover y añade la mitad del perejil picado.',
      'Coloca la merluza y las almejas. Cocina 4–5 minutos por cada lado moviendo la cazuela en círculos para que la salsa ligue.',
      'Espolvorea el resto del perejil y sirve enseguida.',
    ],
  },
  {
    slug: 'bacalao-con-tomate',
    title: 'Bacalao con tomate',
    prep_minutes: 40,
    difficulty: 'facil',
    servings: 4,
    tags: ['pescado'],
    ingredients: [
      i('Bacalao desalado en lomos', '4 lomos', 'carne_pescado'),
      i('Tomate triturado', '800 g', 'despensa'),
      i('Cebolla', '1', 'fruta_verdura'),
      i('Pimiento verde', '1', 'fruta_verdura'),
      i('Ajo', '2 dientes', 'fruta_verdura'),
      i('Harina', 'para rebozar', 'despensa'),
      i('Azúcar', '1 cucharadita', 'despensa'),
      i('Aceite de oliva', 'el necesario', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Seca bien los lomos de bacalao, pásalos por harina y fríelos 2 minutos por cada lado. Reserva.',
      'En una cazuela con un poco de aceite, pocha la cebolla, el pimiento y el ajo picados durante 10 minutos.',
      'Añade el tomate, el azúcar y una pizca de sal. Cocina a fuego suave 15 minutos.',
      'Coloca el bacalao sobre el tomate y cocina 5 minutos más con la cazuela tapada.',
      'Sirve caliente.',
    ],
  },
  {
    slug: 'pollo-al-ajillo',
    title: 'Pollo al ajillo',
    prep_minutes: 45,
    difficulty: 'facil',
    servings: 4,
    tags: ['carne'],
    ingredients: [
      i('Pollo troceado', '1 (1,5 kg)', 'carne_pescado'),
      i('Ajo', '1 cabeza', 'fruta_verdura'),
      i('Vino blanco', '1 vaso', 'bebidas'),
      i('Hoja de laurel', '1', 'despensa'),
      i('Perejil fresco', 'un puñado', 'fruta_verdura'),
      i('Aceite de oliva', '6 cucharadas', 'despensa'),
      i('Sal y pimienta', 'al gusto', 'despensa'),
    ],
    steps: [
      'Salpimienta el pollo.',
      'En una cazuela con el aceite, dora el pollo a fuego medio-alto por todos los lados (unos 15 minutos). Sácalo.',
      'En el mismo aceite, dora los ajos enteros con piel (ligeramente aplastados) y el laurel.',
      'Vuelve a meter el pollo, añade el vino y deja que se evapore el alcohol 2 minutos.',
      'Tapa y cocina a fuego suave 20 minutos, removiendo de vez en cuando. Si se seca, añade un poco de agua.',
      'Espolvorea el perejil picado y sirve.',
    ],
  },
  {
    slug: 'albondigas-en-salsa',
    title: 'Albóndigas en salsa',
    prep_minutes: 60,
    difficulty: 'media',
    servings: 4,
    tags: ['carne'],
    ingredients: [
      i('Carne picada mixta', '600 g', 'carne_pescado'),
      i('Huevo', '1', 'lacteos_huevos'),
      i('Pan rallado', '3 cucharadas', 'despensa'),
      i('Leche', 'un chorrito', 'lacteos_huevos'),
      i('Ajo', '2 dientes', 'fruta_verdura'),
      i('Perejil fresco', 'un puñado', 'fruta_verdura'),
      i('Cebolla', '1', 'fruta_verdura'),
      i('Zanahoria', '1', 'fruta_verdura'),
      i('Harina', 'para rebozar', 'despensa'),
      i('Vino blanco', '1/2 vaso', 'bebidas'),
      i('Caldo de carne o pollo', '1 vaso', 'despensa'),
      i('Aceite de oliva', 'el necesario', 'despensa'),
      i('Sal y pimienta', 'al gusto', 'despensa'),
    ],
    steps: [
      'Mezcla la carne con el huevo, el pan rallado mojado en leche, un ajo y el perejil picados, sal y pimienta.',
      'Forma bolas del tamaño de una nuez, pásalas por harina y fríelas hasta que estén doradas. Reserva.',
      'En una cazuela con 3 cucharadas de aceite, pocha la cebolla, la zanahoria y el otro ajo picados unos 10 minutos.',
      'Añade el vino y deja evaporar 2 minutos. Echa el caldo y cuece 10 minutos.',
      'Tritura la salsa, vuelve a ponerla en la cazuela con las albóndigas y cuece todo junto 15 minutos a fuego suave.',
      'Sirve con arroz blanco o patatas fritas.',
    ],
  },
  {
    slug: 'paella-mixta',
    title: 'Paella mixta',
    prep_minutes: 60,
    difficulty: 'media',
    servings: 4,
    tags: ['carne', 'pescado'],
    ingredients: [
      i('Arroz redondo', '400 g', 'despensa'),
      i('Pollo troceado', '1/2', 'carne_pescado'),
      i('Calamares', '250 g', 'carne_pescado'),
      i('Gambas', '12', 'carne_pescado'),
      i('Mejillones', '500 g', 'carne_pescado'),
      i('Pimiento rojo', '1', 'fruta_verdura'),
      i('Tomate', '2 maduros', 'fruta_verdura'),
      i('Ajo', '2 dientes', 'fruta_verdura'),
      i('Guisantes', '100 g', 'congelados'),
      i('Caldo de pescado', '1,2 litros', 'despensa'),
      i('Azafrán o colorante', 'una pizca', 'despensa'),
      i('Pimentón dulce', '1 cucharadita', 'despensa'),
      i('Aceite de oliva', '6 cucharadas', 'despensa'),
      i('Limón', '1', 'fruta_verdura'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Abre los mejillones al vapor en una olla tapada y reserva (cuela y guarda el agua que suelten para el caldo).',
      'En la paellera con el aceite, marca las gambas 1 minuto por lado y sácalas.',
      'Dora el pollo salado a fuego medio durante 10 minutos. Añade los calamares en anillas y el pimiento en tiras y rehoga 5 minutos.',
      'Añade el ajo picado y el tomate rallado y sofríe 5 minutos. Echa el pimentón, remueve y añade el arroz. Nácara 1 minuto.',
      'Vierte el caldo caliente con el azafrán, prueba de sal y reparte bien el arroz. A partir de aquí no se remueve.',
      'Cuece 10 minutos a fuego fuerte y 8 minutos a fuego suave. A mitad, añade los guisantes.',
      'Coloca encima las gambas y los mejillones. Apaga, tapa con un paño y deja reposar 5 minutos.',
      'Sirve con gajos de limón.',
    ],
  },
  {
    slug: 'macarrones-con-chorizo',
    title: 'Macarrones con tomate y chorizo',
    prep_minutes: 25,
    difficulty: 'facil',
    servings: 4,
    tags: ['rapida', 'carne'],
    ingredients: [
      i('Macarrones', '400 g', 'despensa'),
      i('Chorizo', '150 g', 'carne_pescado'),
      i('Tomate frito', '400 g', 'despensa'),
      i('Cebolla', '1', 'fruta_verdura'),
      i('Queso rallado', '100 g', 'lacteos_huevos'),
      i('Aceite de oliva', '2 cucharadas', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Cuece los macarrones en abundante agua con sal el tiempo que indique el paquete. Escurre.',
      'Mientras, en una sartén con el aceite, pocha la cebolla picada 8 minutos.',
      'Añade el chorizo en trocitos y rehoga 2 minutos.',
      'Echa el tomate frito y calienta 3 minutos.',
      'Mezcla con la pasta, espolvorea el queso rallado y sirve. (Si quieres, gratina 5 minutos en el horno).',
    ],
  },
  {
    slug: 'pisto-con-huevo',
    title: 'Pisto manchego con huevo',
    prep_minutes: 45,
    difficulty: 'facil',
    servings: 4,
    tags: ['verdura'],
    ingredients: [
      i('Calabacín', '1 grande', 'fruta_verdura'),
      i('Pimiento verde', '1', 'fruta_verdura'),
      i('Pimiento rojo', '1', 'fruta_verdura'),
      i('Cebolla', '1', 'fruta_verdura'),
      i('Tomate triturado', '400 g', 'despensa'),
      i('Huevos', '4', 'lacteos_huevos'),
      i('Azúcar', '1 cucharadita', 'despensa'),
      i('Aceite de oliva', '5 cucharadas', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Pica la cebolla y los pimientos en daditos, y el calabacín en dados un poco más grandes.',
      'En una sartén amplia con el aceite, pocha la cebolla 5 minutos. Añade los pimientos y cocina 10 minutos.',
      'Añade el calabacín con un poco de sal y cocina 10 minutos más.',
      'Incorpora el tomate y el azúcar y deja a fuego suave 15 minutos, removiendo de vez en cuando.',
      'Sirve con un huevo frito encima de cada plato.',
    ],
  },
  {
    slug: 'judias-verdes-con-patatas',
    title: 'Judías verdes con patatas',
    prep_minutes: 30,
    difficulty: 'facil',
    servings: 4,
    tags: ['verdura', 'rapida'],
    ingredients: [
      i('Judías verdes', '600 g', 'fruta_verdura'),
      i('Patatas', '3 medianas', 'fruta_verdura'),
      i('Ajo', '3 dientes', 'fruta_verdura'),
      i('Pimentón dulce', '1/2 cucharadita', 'despensa'),
      i('Jamón en taquitos', '100 g (opcional)', 'carne_pescado'),
      i('Aceite de oliva', '4 cucharadas', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Quita las puntas a las judías y córtalas en trozos. Pela las patatas y córtalas en trozos medianos.',
      'Cuece las patatas en agua con sal 10 minutos. Añade las judías y cuece 10 minutos más. Escurre.',
      'En una sartén con el aceite, dora los ajos laminados (y el jamón, si lo usas).',
      'Aparta del fuego, añade el pimentón y remueve rápido para que no se queme.',
      'Vierte el refrito sobre las verduras, mezcla y sirve.',
    ],
  },
  {
    slug: 'crema-de-calabacin',
    title: 'Crema de calabacín',
    prep_minutes: 30,
    difficulty: 'facil',
    servings: 4,
    tags: ['verdura', 'rapida'],
    ingredients: [
      i('Calabacines', '3', 'fruta_verdura'),
      i('Patata', '1', 'fruta_verdura'),
      i('Cebolla', '1', 'fruta_verdura'),
      i('Quesitos', '4', 'lacteos_huevos'),
      i('Caldo de verduras o agua', '700 ml', 'despensa'),
      i('Aceite de oliva', '2 cucharadas', 'despensa'),
      i('Sal y pimienta', 'al gusto', 'despensa'),
    ],
    steps: [
      'Pica la cebolla y pocha en una olla con el aceite 5 minutos.',
      'Añade el calabacín (con piel) y la patata en trozos y rehoga 3 minutos.',
      'Cubre con el caldo, sala y cuece 15–20 minutos, hasta que la patata esté tierna.',
      'Añade los quesitos y tritura hasta que quede una crema fina.',
      'Prueba de sal y pimienta y sirve caliente.',
    ],
  },
  {
    slug: 'lomo-con-pimientos',
    title: 'Lomo con pimientos',
    prep_minutes: 30,
    difficulty: 'facil',
    servings: 4,
    tags: ['carne', 'rapida'],
    ingredients: [
      i('Lomo de cerdo en filetes', '8 filetes', 'carne_pescado'),
      i('Pimientos verdes italianos', '4', 'fruta_verdura'),
      i('Pimiento rojo', '1', 'fruta_verdura'),
      i('Ajo', '2 dientes', 'fruta_verdura'),
      i('Aceite de oliva', '5 cucharadas', 'despensa'),
      i('Sal', 'al gusto', 'despensa'),
    ],
    steps: [
      'Lava los pimientos y córtalos en tiras.',
      'En una sartén con 4 cucharadas de aceite, fríe los pimientos con el ajo laminado y una pizca de sal a fuego medio unos 15 minutos, hasta que estén blandos. Reserva.',
      'Sala los filetes de lomo.',
      'En otra sartén bien caliente con una cucharada de aceite, haz los filetes 1–2 minutos por cada lado.',
      'Sirve el lomo con los pimientos por encima.',
    ],
  },
]
