import { r } from '../ideas/build'

/**
 * Recetas saludables que se cargan en el recetario (filtro «Saludable").
 * Basadas en lo que Tomás suele comer. Raciones para 2 (sirven para dos días).
 */
export const HEALTHY_SEED_RECIPES = [
  r('pollo-boniato-horno', 'Pollo al horno con boniato y pimientos', 45, 'facil', 2, ['saludable', 'carne'],
    ['Pechuga o contramuslos de pollo sin piel|400 g', 'Boniato|1 grande', 'Pimiento rojo|1', 'Cebolla morada|1', 'Pimentón dulce|1 cucharadita', 'Ajo en polvo|1/2 cucharadita', 'Aceite de oliva|2 cucharadas', 'Sal y pimienta|al gusto'],
    ['Precalienta el horno a 200 °C.',
      'Pela el boniato y córtalo en dados de 2 cm. Corta el pimiento y la cebolla en trozos grandes.',
      'Mezcla las verduras en una bandeja con la mitad del aceite, sal y pimentón. Hornea 15 minutos.',
      'Corta el pollo en trozos, sazónalo con sal, pimienta, ajo en polvo y el resto del aceite.',
      'Añade el pollo a la bandeja, remueve y hornea 20 minutos más, hasta que el pollo esté dorado y el boniato tierno.']),
  r('pollo-arroz-verduras', 'Pollo salteado con arroz y verduras', 30, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pechuga de pollo|300 g', 'Arroz (blanco o integral)|150 g', 'Calabacín|1', 'Zanahoria|1', 'Pimiento verde|1', 'Ajo|1 diente', 'Salsa de soja|2 cucharadas', 'Aceite de oliva|1 cucharada'],
    ['Cuece el arroz según el paquete y escúrrelo.',
      'Corta el pollo en tiras y las verduras en bastoncitos.',
      'En una sartén grande bien caliente con el aceite, dora el pollo 5 minutos. Sácalo.',
      'Saltea las verduras con el ajo picado 5 minutos a fuego fuerte (que queden algo crujientes).',
      'Vuelve a meter el pollo, añade el arroz y la soja y saltea 2 minutos más. Listo.']),
  r('ensalada-garbanzos-caballa', 'Ensalada de garbanzos con caballa y tomate cherry', 15, 'facil', 2, ['saludable', 'pescado', 'legumbres', 'rapida'],
    ['Garbanzos cocidos|1 bote (400 g)', 'Caballa en aceite|2 latas', 'Tomate cherry|200 g', 'Pepino|1/2', 'Cebolla morada|1/2', 'Pimiento verde|1/2', 'Aceitunas negras|un puñado', 'Aceite de oliva virgen extra|2 cucharadas', 'Vinagre|1 cucharada', 'Orégano|una pizca', 'Sal|al gusto'],
    ['Enjuaga los garbanzos y escúrrelos bien.',
      'Corta los tomates cherry por la mitad y pica fino el pepino, la cebolla y el pimiento.',
      'Mezcla todo en un bol con las aceitunas y la caballa escurrida en trozos.',
      'Aliña con aceite, vinagre, sal y orégano. Si puedes, deja reposar 10 minutos en la nevera.']),
  r('ensalada-lentejas', 'Ensalada de lentejas con verduras y huevo', 20, 'facil', 2, ['saludable', 'legumbres', 'rapida'],
    ['Lentejas cocidas|1 bote (400 g)', 'Huevos|2', 'Tomate|1', 'Pimiento rojo|1/2', 'Cebolleta|1', 'Maíz dulce|1 lata pequeña', 'Aceite de oliva virgen extra|2 cucharadas', 'Vinagre de manzana|1 cucharada', 'Mostaza|1 cucharadita', 'Sal|al gusto'],
    ['Cuece los huevos 10 minutos, enfríalos y pélalos.',
      'Enjuaga las lentejas y escúrrelas.',
      'Pica el tomate, el pimiento y la cebolleta en daditos.',
      'Bate el aceite con el vinagre, la mostaza y una pizca de sal.',
      'Mezcla lentejas, verduras y maíz, aliña y pon el huevo en cuartos por encima.']),
  r('merluza-horno-verduras', 'Merluza al horno con verduritas', 35, 'facil', 2, ['saludable', 'pescado'],
    ['Lomos de merluza|2 (unos 300 g)', 'Patata|1', 'Calabacín|1', 'Cebolla|1', 'Tomate|1', 'Ajo|2 dientes', 'Perejil fresco|un poco', 'Limón|1/2', 'Aceite de oliva|2 cucharadas', 'Sal|al gusto'],
    ['Precalienta el horno a 200 °C.',
      'Corta la patata en rodajas finas y la cebolla, el calabacín y el tomate en rodajas.',
      'Ponlos en una fuente con 1 cucharada de aceite y sal. Hornea 20 minutos.',
      'Coloca la merluza encima, con sal, el ajo y el perejil picados, unas gotas de limón y el resto del aceite.',
      'Hornea 10–12 minutos más, hasta que el pescado se separe en láminas.']),
  r('salmon-horno-esparragos', 'Salmón al horno con espárragos y patatas', 35, 'facil', 2, ['saludable', 'pescado'],
    ['Lomos de salmón|2', 'Espárragos verdes|1 manojo', 'Patatas pequeñas|300 g', 'Limón|1', 'Eneldo o perejil|al gusto', 'Aceite de oliva|2 cucharadas', 'Sal y pimienta|al gusto'],
    ['Precalienta el horno a 200 °C. Corta las patatas por la mitad y hornéalas 15 minutos con un poco de aceite y sal.',
      'Quita la parte dura de los espárragos.',
      'Añade a la bandeja los espárragos y el salmón con sal, pimienta, el resto del aceite, rodajas de limón y el eneldo.',
      'Hornea 12–15 minutos. El salmón debe quedar jugoso por dentro.']),
  r('lasana-berenjena', 'Lasaña de berenjena con carne picada', 60, 'media', 3, ['saludable', 'carne', 'verdura'],
    ['Berenjenas|2 grandes', 'Carne picada de ternera o pavo|300 g', 'Cebolla|1', 'Zanahoria|1', 'Ajo|1 diente', 'Tomate triturado|400 g', 'Mozzarella rallada ligera|100 g', 'Orégano|1 cucharadita', 'Aceite de oliva|1 cucharada', 'Sal y pimienta|al gusto'],
    ['Corta las berenjenas en láminas a lo largo, sálalas y hornéalas 15 minutos a 200 °C (o hazlas a la plancha).',
      'Sofríe la cebolla, la zanahoria y el ajo picados en el aceite 8 minutos.',
      'Añade la carne, dórala, echa el tomate y el orégano y cocina 15 minutos. Salpimienta.',
      'En una fuente alterna capas de berenjena y carne. Termina con berenjena y la mozzarella.',
      'Hornea 20 minutos a 190 °C y gratina 3 minutos al final. Deja reposar 5 minutos antes de cortar.']),
  r('bowl-pollo-aguacate', 'Bowl de pollo, arroz integral y aguacate', 30, 'facil', 2, ['saludable', 'carne'],
    ['Pechuga de pollo|300 g', 'Arroz integral|120 g', 'Aguacate|1', 'Tomate cherry|150 g', 'Maíz dulce|1 lata pequeña', 'Hojas verdes (canónigos o rúcula)|2 puñados', 'Yogur natural|1', 'Limón|1/2', 'Pimentón dulce|1/2 cucharadita', 'Sal|al gusto'],
    ['Cuece el arroz integral (unos 25 minutos) y escúrrelo.',
      'Sazona el pollo con sal y pimentón y hazlo a la plancha 4–5 minutos por lado. Córtalo en tiras.',
      'Mezcla el yogur con el zumo de limón y una pizca de sal para la salsa.',
      'Monta los boles: base de hojas y arroz, y encima el pollo, el aguacate, los tomates y el maíz. Riega con la salsa.']),
  r('tortilla-espinacas-champis', 'Tortilla de espinacas y champiñones con ensalada', 20, 'facil', 2, ['saludable', 'verdura', 'rapida'],
    ['Huevos|4', 'Espinacas frescas|100 g', 'Champiñones|150 g', 'Ajo|1 diente', 'Tomate|2', 'Lechuga|1/2', 'Aceite de oliva|1 cucharada', 'Sal|al gusto'],
    ['Lamina los champiñones y saltéalos con el ajo picado en la mitad del aceite 4 minutos.',
      'Añade las espinacas y deja que se reduzcan 2 minutos.',
      'Bate los huevos con sal, mézclalos con las verduras y cuaja la tortilla en una sartén con el resto del aceite, 2–3 minutos por lado.',
      'Sirve con una ensalada de lechuga y tomate.']),
  r('dorada-horno-limon', 'Dorada al horno con limón y patatas', 40, 'facil', 2, ['saludable', 'pescado'],
    ['Doradas limpias|2 (o 4 lomos)', 'Patatas|2', 'Cebolla|1', 'Limón|1', 'Ajo|2 dientes', 'Vino blanco|1/2 vaso', 'Aceite de oliva|2 cucharadas', 'Sal|al gusto'],
    ['Precalienta el horno a 200 °C.',
      'Corta las patatas y la cebolla en rodajas finas, ponlas en una fuente con sal y 1 cucharada de aceite y hornea 20 minutos.',
      'Haz 2 cortes en el lomo de cada dorada y mete en ellos media rodaja de limón. Sala.',
      'Coloca el pescado sobre las patatas, añade el vino, el ajo laminado y el resto del aceite.',
      'Hornea 15–18 minutos.']),
  r('pavo-wok-verduras', 'Salteado de pavo con verduras al wok', 20, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pechuga de pavo|300 g', 'Brócoli|1/2', 'Pimiento rojo|1', 'Zanahoria|1', 'Cebolleta|1', 'Jengibre fresco|un trocito', 'Salsa de soja|2 cucharadas', 'Miel|1 cucharadita', 'Semillas de sésamo|1 cucharada', 'Aceite de oliva|1 cucharada'],
    ['Corta el pavo en tiras y las verduras en trozos pequeños. El brócoli, en ramilletes.',
      'Saltea el pavo en el wok o sartén grande muy caliente con el aceite 4 minutos. Sácalo.',
      'Saltea las verduras con el jengibre rallado 5 minutos, que queden al dente.',
      'Vuelve a meter el pavo, añade la soja y la miel y saltea 1 minuto.',
      'Sirve con sésamo por encima (solo o con un poco de arroz).']),
  r('quinoa-pollo-templada', 'Ensalada templada de quinoa con pollo y verduras asadas', 35, 'facil', 2, ['saludable', 'carne'],
    ['Quinoa|120 g', 'Pechuga de pollo|250 g', 'Calabacín|1', 'Pimiento rojo|1', 'Cebolla morada|1/2', 'Espinacas frescas|1 puñado', 'Limón|1/2', 'Aceite de oliva|2 cucharadas', 'Comino molido|1/2 cucharadita', 'Sal|al gusto'],
    ['Lava la quinoa y cuécela 12–15 minutos en el doble de agua con sal. Escúrrela.',
      'Corta las verduras en dados y ásalas 20 minutos a 200 °C con 1 cucharada de aceite, sal y comino.',
      'Haz el pollo a la plancha y córtalo en dados.',
      'Mezcla la quinoa con las verduras, el pollo y las espinacas. Aliña con el resto del aceite y el limón.']),
]
