import { r } from './build'

/** Ideas saludables (2/2): legumbres, pasta, arroz, pizza, huevos y verdura. Raciones para 2. */
export const HEALTHY_POOL_2 = [
  r('hummus-bowl-pollo', 'Bowl de hummus con pollo y verduras', 25, 'facil', 2, ['saludable', 'legumbres', 'carne'],
    ['Garbanzos cocidos|1 bote (400 g)', 'Tahini (o 1 cucharada de aceite extra)|1 cucharada', 'Limón|1', 'Ajo|1/2 diente', 'Comino|una pizca', 'Pechuga de pollo|250 g', 'Pepino|1/2', 'Tomate cherry|150 g', 'Pimentón|una pizca', 'Aceite de oliva|2 cucharadas'],
    ['Tritura los garbanzos con el tahini, el zumo de limón, el ajo, el comino, sal y un chorrito de agua hasta que quede cremoso.', 'Haz el pollo a la plancha con sal y pimentón y córtalo en tiras.', 'Pon una base de hummus en cada bol y encima el pollo, el pepino y los tomates.', 'Termina con aceite y pimentón.']),
  r('garbanzos-curry-espinacas', 'Garbanzos al curry con espinacas', 30, 'facil', 2, ['saludable', 'legumbres', 'verdura', 'rapida'],
    ['Garbanzos cocidos|1 bote (400 g)', 'Espinacas frescas|150 g', 'Cebolla|1', 'Ajo|1 diente', 'Curry en polvo|2 cucharaditas', 'Tomate triturado|200 g', 'Leche de coco ligera o yogur|100 ml', 'Aceite de oliva|1 cucharada', 'Arroz basmati|100 g (opcional)'],
    ['Pocha la cebolla y el ajo picados 6 minutos.', 'Añade el curry, remueve 1 minuto y echa el tomate. Cocina 5 minutos.', 'Incorpora los garbanzos escurridos y la leche de coco y cocina 10 minutos.', 'Añade las espinacas hasta que se reduzcan. Sirve solo o con arroz.']),
  r('dal-lentejas-rojas', 'Lentejas rojas al estilo indio (dal)', 35, 'facil', 3, ['saludable', 'legumbres', 'verdura'],
    ['Lentejas rojas (coral)|200 g', 'Cebolla|1', 'Ajo|2 dientes', 'Jengibre fresco|un trocito', 'Tomate|2', 'Curry en polvo|1 cucharadita', 'Comino|1/2 cucharadita', 'Cúrcuma|1/2 cucharadita', 'Espinacas|1 puñado', 'Aceite de oliva|1 cucharada'],
    ['Pocha la cebolla, el ajo y el jengibre picados 6 minutos. Añade las especias y remueve 1 minuto.', 'Incorpora el tomate picado y cocina 3 minutos.', 'Añade las lentejas lavadas y 700 ml de agua. Cuece 20 minutos, removiendo, hasta que queden cremosas.', 'Añade las espinacas y sal al final.']),
  r('chili-sin-carne', 'Chili sin carne', 40, 'facil', 3, ['saludable', 'legumbres', 'verdura'],
    ['Alubias rojas cocidas|1 bote (400 g)', 'Lentejas cocidas|1/2 bote', 'Pimiento rojo|1', 'Cebolla|1', 'Zanahoria|1', 'Maíz dulce|1 lata pequeña', 'Tomate triturado|400 g', 'Comino|1 cucharadita', 'Pimentón|1 cucharadita', 'Aceite de oliva|1 cucharada'],
    ['Pocha la cebolla, el pimiento y la zanahoria picados 10 minutos.', 'Añade las especias, remueve y echa el tomate. Cocina 10 minutos.', 'Incorpora alubias, lentejas y maíz escurridos y cocina 10 minutos más.', 'Sirve con un poco de arroz, yogur o aguacate.']),
  r('alubias-verduras', 'Alubias blancas con verduras', 40, 'facil', 3, ['saludable', 'legumbres', 'verdura'],
    ['Alubias blancas cocidas|2 botes (800 g)', 'Puerro|1', 'Zanahoria|2', 'Pimiento verde|1', 'Calabacín|1/2', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Caldo de verduras|500 ml', 'Aceite de oliva|2 cucharadas'],
    ['Pica todas las verduras.', 'Pocha el puerro, el ajo, la zanahoria y el pimiento 10 minutos. Añade el calabacín 3 minutos.', 'Echa el pimentón, remueve y añade el caldo. Cuece 10 minutos.', 'Añade las alubias enjuagadas y cocina 10 minutos más a fuego suave.']),
  r('ensalada-alubias-atun', 'Ensalada de alubias con atún y pimiento', 15, 'facil', 2, ['saludable', 'legumbres', 'pescado', 'rapida'],
    ['Alubias blancas cocidas|1 bote (400 g)', 'Atún al natural|2 latas', 'Pimiento rojo asado o fresco|1', 'Cebolleta|1', 'Tomate|1', 'Perejil fresco|un poco', 'Aceite de oliva virgen extra|2 cucharadas', 'Vinagre|1 cucharada'],
    ['Enjuaga y escurre las alubias.', 'Pica el pimiento, la cebolleta y el tomate.', 'Mezcla todo con el atún y el perejil y aliña con aceite, vinagre y sal.']),
  r('falafel-horno', 'Falafel al horno con salsa de yogur', 45, 'media', 2, ['saludable', 'legumbres'],
    ['Garbanzos cocidos|1 bote (400 g)', 'Cebolla|1/2', 'Ajo|1 diente', 'Perejil o cilantro|un puñado', 'Comino|1 cucharadita', 'Harina|2 cucharadas', 'Yogur natural|1', 'Limón|1/2', 'Tomate y lechuga|para la ensalada', 'Aceite de oliva|1 cucharada'],
    ['Seca bien los garbanzos y tritúralos (sin que queden puré) con la cebolla, el ajo, el perejil, el comino, sal y la harina.', 'Forma bolitas algo aplastadas y ponlas en una bandeja con papel. Píntalas con aceite.', 'Hornea 25 minutos a 200 °C, dándoles la vuelta a mitad.', 'Sirve con ensalada y el yogur mezclado con limón y sal.']),
  r('burger-lentejas', 'Hamburguesas de lentejas con ensalada', 40, 'media', 2, ['saludable', 'legumbres'],
    ['Lentejas cocidas|1 bote (400 g)', 'Zanahoria|1', 'Cebolla|1/2', 'Copos de avena|4 cucharadas', 'Huevo|1', 'Comino|1/2 cucharadita', 'Pimentón|1/2 cucharadita', 'Lechuga y tomate|para acompañar', 'Aceite de oliva|1 cucharada'],
    ['Escurre muy bien las lentejas y cháfalas con un tenedor.', 'Ralla la zanahoria, pica la cebolla y mézclalo todo con la avena, el huevo, las especias y sal.', 'Forma 4 hamburguesas y deja reposar 10 minutos en la nevera.', 'Hazlas a la plancha con el aceite 3–4 minutos por lado. Sirve con ensalada.']),
  r('lentejas-arroz-verduras', 'Lentejas con arroz y verduras', 45, 'facil', 3, ['saludable', 'legumbres', 'verdura'],
    ['Lentejas pardinas|200 g', 'Arroz|60 g', 'Cebolla|1', 'Zanahoria|1', 'Pimiento verde|1', 'Tomate|1', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Laurel|1 hoja', 'Aceite de oliva|2 cucharadas'],
    ['Sofríe la cebolla, el pimiento, la zanahoria y el ajo picados 8 minutos. Añade el tomate rallado 3 minutos.', 'Echa el pimentón, las lentejas lavadas, el laurel y 1,2 litros de agua. Cuece 25 minutos.', 'Añade el arroz y cuece 15 minutos más. Ajusta de sal.']),
  r('potaje-garbanzos-verduras', 'Potaje de garbanzos con verduras', 45, 'facil', 3, ['saludable', 'legumbres', 'verdura'],
    ['Garbanzos cocidos|2 botes (800 g)', 'Patata|1', 'Zanahoria|2', 'Judías verdes|150 g', 'Cebolla|1', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Comino|una pizca', 'Caldo de verduras|700 ml', 'Aceite de oliva|2 cucharadas'],
    ['Sofríe la cebolla y el ajo 6 minutos. Añade el pimentón y el comino.', 'Incorpora la patata y la zanahoria en trozos y el caldo. Cuece 15 minutos.', 'Añade las judías troceadas y los garbanzos escurridos y cuece 10 minutos más.']),
  r('ensalada-garbanzos-pepino-queso', 'Ensalada de garbanzos, pepino y queso fresco', 15, 'facil', 2, ['saludable', 'legumbres', 'rapida', 'verdura'],
    ['Garbanzos cocidos|1 bote (400 g)', 'Pepino|1', 'Tomate cherry|150 g', 'Queso fresco|100 g', 'Cebolla morada|1/4', 'Hierbabuena o perejil|un poco', 'Limón|1/2', 'Aceite de oliva virgen extra|2 cucharadas'],
    ['Enjuaga y escurre los garbanzos.', 'Corta el pepino, los tomates y el queso en dados y pica la cebolla.', 'Mezcla todo y aliña con aceite, limón, sal y la hierba picada.']),
  r('coliflor-curry-garbanzos', 'Coliflor asada al curry con garbanzos', 40, 'facil', 2, ['saludable', 'legumbres', 'verdura'],
    ['Coliflor|1', 'Garbanzos cocidos|1 bote (400 g)', 'Curry en polvo|2 cucharaditas', 'Yogur natural|1', 'Limón|1/2', 'Perejil o cilantro|un poco', 'Aceite de oliva|2 cucharadas'],
    ['Precalienta el horno a 210 °C.', 'Corta la coliflor en ramilletes y mézclala con los garbanzos escurridos y secos, el aceite, el curry y sal.', 'Hornea 25–30 minutos, removiendo a mitad, hasta que se tuesten.', 'Sirve con el yogur mezclado con limón y la hierba picada.']),
  r('carbonara', 'Espaguetis a la carbonara (la de verdad)', 25, 'media', 2, ['carne'],
    ['Espaguetis|180 g', 'Guanciale o panceta curada|80 g', 'Yemas de huevo|2', 'Huevo|1', 'Queso pecorino o parmesano rallado|40 g', 'Pimienta negra|al gusto'],
    ['Cuece la pasta en abundante agua con sal. Guarda un vaso del agua de cocción.', 'Mientras, dora la panceta en tiras en una sartén sin aceite hasta que suelte la grasa. Apaga el fuego.', 'Bate las yemas y el huevo con el queso y mucha pimienta.', 'Echa la pasta escurrida a la sartén (fuera del fuego), añade el huevo y un chorrito del agua de cocción y remueve rápido hasta que quede una crema. Sin nata.']),
  r('pasta-pesto-pollo', 'Pasta integral con pesto y pollo', 25, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pasta integral|160 g', 'Pechuga de pollo|200 g', 'Pesto|3 cucharadas', 'Tomate cherry|150 g', 'Rúcula o espinacas|1 puñado', 'Parmesano|20 g', 'Aceite de oliva|1 cucharada'],
    ['Cuece la pasta.', 'Haz el pollo a la plancha y córtalo en tiras. Saltea los tomates partidos 2 minutos.', 'Mezcla la pasta escurrida con el pesto, el pollo, los tomates y la rúcula.', 'Termina con parmesano rallado.']),
  r('ensalada-pasta-atun', 'Ensalada de pasta con atún, tomate y aceitunas', 20, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Pasta corta (fusilli, lazos…)|160 g', 'Atún al natural|2 latas', 'Tomate cherry|200 g', 'Aceitunas negras|un puñado', 'Pepino|1/2', 'Mozzarella fresca o queso fresco|100 g', 'Albahaca u orégano|al gusto', 'Aceite de oliva virgen extra|2 cucharadas'],
    ['Cuece la pasta y enfríala bajo el grifo.', 'Corta los tomates, el pepino y el queso.', 'Mezcla todo con el atún y las aceitunas.', 'Aliña con aceite, sal y la albahaca.']),
  r('bolonesa-pavo', 'Espaguetis a la boloñesa de pavo', 40, 'facil', 3, ['saludable', 'carne'],
    ['Espaguetis|240 g', 'Carne picada de pavo|300 g', 'Cebolla|1', 'Zanahoria|1', 'Apio|1 rama (opcional)', 'Ajo|1 diente', 'Tomate triturado|400 g', 'Orégano|1 cucharadita', 'Aceite de oliva|1 cucharada', 'Parmesano|al gusto'],
    ['Pica muy fino la cebolla, la zanahoria, el apio y el ajo, y pócha todo 10 minutos.', 'Añade el pavo y dóralo bien.', 'Echa el tomate y el orégano y cocina 20 minutos a fuego suave.', 'Cuece la pasta, mezcla con la salsa y sirve con un poco de parmesano.']),
  r('pasta-gambas-calabacin', 'Pasta con gambas, calabacín y limón', 25, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Pasta|160 g', 'Gambas peladas|200 g', 'Calabacín|1', 'Ajo|2 dientes', 'Limón|1', 'Guindilla|1 (opcional)', 'Perejil fresco|un poco', 'Aceite de oliva|2 cucharadas'],
    ['Cuece la pasta y guarda un poco del agua.', 'Saltea el calabacín en dados 4 minutos con el aceite y el ajo. Añade las gambas y la guindilla 2 minutos.', 'Mezcla con la pasta, la ralladura y el zumo de limón y un chorrito del agua de cocción.', 'Termina con perejil.']),
  r('pizza-casera-integral', 'Pizza casera integral de pollo y verduras (para el domingo)', 60, 'media', 2, ['saludable', 'carne'],
    ['Harina integral|200 g', 'Levadura de panadería seca|1 sobre (5 g)', 'Agua templada|130 ml', 'Tomate triturado|150 g', 'Mozzarella ligera|125 g', 'Pechuga de pollo|150 g', 'Pimiento rojo|1/2', 'Champiñones|100 g', 'Cebolla morada|1/2', 'Orégano|1 cucharadita', 'Aceite de oliva|2 cucharadas'],
    ['Mezcla la harina, la levadura, una pizca de sal, el agua y 1 cucharada de aceite. Amasa 5 minutos y deja reposar tapada 30 minutos.', 'Mientras, haz el pollo a la plancha en tiras y corta las verduras.', 'Estira la masa fina sobre papel de horno. Unta el tomate con sal y orégano.', 'Pon la mozzarella, el pollo y las verduras.', 'Hornea 12–15 minutos a 230 °C.']),
  r('pizza-tortilla-express', 'Pizza exprés sobre tortilla de trigo', 15, 'facil', 2, ['saludable', 'rapida'],
    ['Tortillas de trigo integrales|2', 'Tomate triturado|4 cucharadas', 'Mozzarella ligera|100 g', 'Jamón cocido o pavo|4 lonchas', 'Champiñones|4', 'Rúcula|1 puñado', 'Orégano|una pizca'],
    ['Precalienta el horno a 220 °C.', 'Unta las tortillas con el tomate y espolvorea orégano.', 'Pon la mozzarella, el jamón y los champiñones laminados.', 'Hornea 8 minutos, hasta que la base esté crujiente. Pon la rúcula al sacarla.']),
  r('risotto-champis', 'Risotto de champiñones', 40, 'media', 2, ['saludable', 'verdura'],
    ['Arroz redondo o arborio|160 g', 'Champiñones o setas|250 g', 'Cebolla|1/2', 'Ajo|1 diente', 'Vino blanco|1/2 vaso', 'Caldo de verduras caliente|700 ml', 'Parmesano|30 g', 'Aceite de oliva|1 cucharada', 'Perejil fresco|un poco'],
    ['Saltea los champiñones laminados 5 minutos y resérvalos.', 'Pocha la cebolla y el ajo. Añade el arroz y remueve 1 minuto. Echa el vino hasta que se evapore.', 'Ve añadiendo el caldo poco a poco, removiendo, durante unos 18 minutos.', 'Incorpora los champiñones y el parmesano, remueve y deja reposar 2 minutos. Termina con perejil.']),
  r('arroz-tres-delicias', 'Arroz tres delicias casero', 30, 'facil', 2, ['saludable', 'rapida'],
    ['Arroz cocido (mejor del día anterior)|300 g', 'Huevos|2', 'Jamón cocido|100 g', 'Guisantes|80 g', 'Zanahoria|1', 'Gambas peladas|100 g (opcional)', 'Salsa de soja|2 cucharadas', 'Aceite de oliva|1 cucharada'],
    ['Cuece los guisantes y la zanahoria en daditos 5 minutos.', 'Haz una tortilla fina con los huevos y córtala en tiras.', 'Saltea las gambas y el jamón en dados 2 minutos.', 'Añade el arroz, las verduras y la tortilla y saltea a fuego fuerte 3 minutos con la soja.']),
  r('arroz-verduras-gambas', 'Arroz con verduras y gambas', 40, 'media', 2, ['saludable', 'pescado'],
    ['Arroz redondo|160 g', 'Gambas|200 g', 'Pimiento rojo|1/2', 'Judías verdes|100 g', 'Alcachofas (o de bote)|2', 'Tomate|1', 'Ajo|1 diente', 'Pimentón dulce|1/2 cucharadita', 'Caldo de pescado|500 ml', 'Aceite de oliva|2 cucharadas'],
    ['Marca las gambas en la paella 1 minuto y sácalas.', 'Sofríe el pimiento, las judías y las alcachofas 8 minutos. Añade el ajo y el tomate rallado 3 minutos.', 'Echa el pimentón, el arroz y el caldo caliente. Cuece 17 minutos sin remover.', 'Pon las gambas encima los últimos 3 minutos y deja reposar 5.']),
  r('macarrones-atun-tomate', 'Macarrones integrales con atún y tomate', 25, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Macarrones integrales|160 g', 'Atún al natural|2 latas', 'Tomate triturado|300 g', 'Cebolla|1', 'Orégano|1 cucharadita', 'Queso rallado|30 g', 'Aceite de oliva|1 cucharada'],
    ['Cuece la pasta.', 'Pocha la cebolla, añade el tomate y el orégano y cocina 10 minutos.', 'Añade el atún escurrido y mezcla con la pasta.', 'Sirve con un poco de queso (o gratina 5 minutos).']),
  r('lasana-calabacin-pollo', 'Lasaña de calabacín y pollo', 55, 'media', 3, ['saludable', 'carne', 'verdura'],
    ['Calabacines|2', 'Carne picada de pollo|300 g', 'Cebolla|1', 'Tomate triturado|300 g', 'Espinacas|1 puñado', 'Queso fresco batido|150 g', 'Mozzarella ligera|100 g', 'Orégano|1 cucharadita', 'Aceite de oliva|1 cucharada'],
    ['Corta los calabacines en láminas a lo largo y márcalos a la plancha.', 'Pocha la cebolla, dora el pollo, añade el tomate, el orégano y las espinacas y cocina 10 minutos.', 'Monta capas de calabacín, pollo y queso batido. Termina con calabacín y mozzarella.', 'Hornea 25 minutos a 190 °C.']),
  r('pasta-gratinada-verduras', 'Pasta gratinada con verduras y mozzarella', 40, 'facil', 3, ['saludable', 'verdura'],
    ['Pasta corta|240 g', 'Calabacín|1', 'Berenjena|1/2', 'Pimiento rojo|1', 'Cebolla|1', 'Tomate triturado|400 g', 'Mozzarella ligera|125 g', 'Albahaca u orégano|al gusto', 'Aceite de oliva|1 cucharada'],
    ['Cuece la pasta 2 minutos menos de lo que indique el paquete.', 'Saltea las verduras en dados 10 minutos, añade el tomate y las hierbas y cocina 10 minutos.', 'Mezcla con la pasta en una fuente y cubre con la mozzarella.', 'Gratina 10 minutos a 220 °C.']),
  r('pasta-salmon-espinacas', 'Pasta con salmón y espinacas', 25, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Pasta|160 g', 'Salmón fresco|200 g', 'Espinacas frescas|100 g', 'Ajo|1 diente', 'Queso fresco batido o leche evaporada ligera|100 g', 'Limón|1/2', 'Aceite de oliva|1 cucharada'],
    ['Cuece la pasta.', 'Dora el salmón en dados con el ajo 3 minutos.', 'Añade las espinacas y el queso batido, con un chorrito del agua de cocción, y mezcla.', 'Junta con la pasta, ralla un poco de limón por encima y sirve.']),
  r('noquis-tomate-espinacas', 'Ñoquis con tomate, espinacas y mozzarella', 20, 'facil', 2, ['saludable', 'verdura', 'rapida'],
    ['Ñoquis de patata|400 g', 'Tomate triturado|300 g', 'Ajo|1 diente', 'Espinacas frescas|100 g', 'Mozzarella fresca|1 bola', 'Albahaca|unas hojas', 'Aceite de oliva|1 cucharada'],
    ['Dora el ajo en el aceite, añade el tomate y cocina 8 minutos con sal.', 'Cuece los ñoquis hasta que floten (2–3 minutos) y pásalos a la salsa.', 'Añade las espinacas y la mozzarella en trozos y deja que se funda 2 minutos. Termina con albahaca.']),
  r('shakshuka', 'Shakshuka (huevos en salsa de tomate especiada)', 30, 'facil', 2, ['saludable', 'verdura'],
    ['Huevos|4', 'Tomate triturado|400 g', 'Pimiento rojo|1', 'Cebolla|1', 'Ajo|2 dientes', 'Comino|1 cucharadita', 'Pimentón|1 cucharadita', 'Perejil o cilantro|un poco', 'Pan integral|para acompañar', 'Aceite de oliva|1 cucharada'],
    ['Pocha la cebolla, el pimiento y el ajo 10 minutos. Añade las especias.', 'Echa el tomate y cocina 10 minutos, hasta que espese. Sala.', 'Haz 4 huecos y casca un huevo en cada uno. Tapa y cocina 5–6 minutos, hasta que la clara cuaje.', 'Termina con perejil y moja con pan.']),
  r('frittata-verduras', 'Frittata de verduras al horno', 30, 'facil', 2, ['saludable', 'verdura'],
    ['Huevos|5', 'Calabacín|1/2', 'Pimiento rojo|1/2', 'Cebolla|1/2', 'Espinacas|1 puñado', 'Queso rallado|30 g', 'Aceite de oliva|1 cucharada', 'Ensalada verde|para acompañar'],
    ['Saltea las verduras en dados 8 minutos en una sartén apta para horno.', 'Bate los huevos con el queso y sal y viértelos sobre las verduras.', 'Cuaja 3 minutos al fuego y termina 10 minutos en el horno a 190 °C.', 'Sirve en porciones con ensalada.']),
  r('calabacines-rellenos-atun', 'Calabacines rellenos de atún', 40, 'facil', 2, ['saludable', 'pescado', 'verdura'],
    ['Calabacines|2', 'Atún al natural|2 latas', 'Cebolla|1/2', 'Tomate triturado|150 g', 'Huevo cocido|1', 'Queso rallado ligero|40 g', 'Aceite de oliva|1 cucharada'],
    ['Parte los calabacines a lo largo, vacíalos con una cuchara y pica la pulpa.', 'Pocha la cebolla, añade la pulpa 5 minutos y el tomate 5 minutos más. Mezcla con el atún y el huevo picado.', 'Rellena los calabacines, pon el queso y hornea 25 minutos a 190 °C.']),
  r('crema-calabaza', 'Crema de calabaza con picatostes integrales', 35, 'facil', 3, ['saludable', 'verdura'],
    ['Calabaza|600 g', 'Zanahoria|2', 'Cebolla|1', 'Patata|1 pequeña', 'Caldo de verduras|700 ml', 'Pan integral|2 rebanadas', 'Pipas de calabaza|1 puñado', 'Aceite de oliva|1 cucharada', 'Nuez moscada|una pizca'],
    ['Pocha la cebolla 5 minutos. Añade la calabaza, la zanahoria y la patata en trozos.', 'Cubre con el caldo y cuece 20 minutos.', 'Tritura con la nuez moscada y sal.', 'Sirve con picatostes (pan tostado en dados) y pipas.']),
  r('verduras-asadas-queso', 'Verduras asadas con queso fresco a la plancha', 35, 'facil', 2, ['saludable', 'verdura'],
    ['Berenjena|1', 'Calabacín|1', 'Pimiento rojo|1', 'Cebolla|1', 'Tomate|2', 'Queso fresco de Burgos|200 g', 'Orégano|una pizca', 'Aceite de oliva|2 cucharadas'],
    ['Corta las verduras en trozos, alíñalas con aceite y sal y ásalas 25–30 minutos a 210 °C.', 'Corta el queso en lonchas gruesas y hazlo a la plancha 1 minuto por lado, que se dore.', 'Sirve las verduras con el queso y orégano.']),
  r('quinoa-verduras-asadas', 'Ensalada templada de quinoa con verduras asadas y feta', 30, 'facil', 2, ['saludable', 'verdura'],
    ['Quinoa|120 g', 'Calabaza|200 g', 'Cebolla morada|1', 'Pimiento rojo|1', 'Queso feta|60 g', 'Rúcula|1 puñado', 'Nueces|un puñado', 'Aceite de oliva|2 cucharadas', 'Vinagre balsámico|1 cucharada'],
    ['Asa las verduras en dados 25 minutos a 200 °C con aceite y sal.', 'Cuece la quinoa lavada 12–15 minutos y escúrrela.', 'Mezcla la quinoa con las verduras, la rúcula, el feta desmigado y las nueces.', 'Aliña con el vinagre y un chorrito de aceite.']),
  r('revuelto-setas-gambas', 'Revuelto de setas y gambas con pan integral', 20, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Huevos|4', 'Setas o champiñones|200 g', 'Gambas peladas|150 g', 'Ajo|2 dientes', 'Perejil fresco|un poco', 'Pan integral|2 rebanadas', 'Aceite de oliva|1 cucharada'],
    ['Saltea el ajo y las setas 5 minutos. Añade las gambas 1 minuto.', 'Baja el fuego, echa los huevos batidos con sal y remueve suave hasta que cuajen, jugosos.', 'Termina con perejil y sirve con pan tostado.']),
  r('tortilla-patata-horno', 'Tortilla de patata al horno (con menos aceite)', 45, 'facil', 2, ['saludable'],
    ['Patatas|400 g', 'Huevos|5', 'Cebolla|1', 'Aceite de oliva|1 cucharada', 'Sal|al gusto', 'Ensalada|para acompañar'],
    ['Corta las patatas en láminas finas y la cebolla en juliana. Mézclalas con el aceite y sal.', 'Hornéalas 25 minutos a 200 °C en una bandeja, removiendo a mitad, hasta que estén tiernas.', 'Mézclalas con los huevos batidos.', 'Cuaja en una sartén antiadherente a fuego medio 3 minutos por lado. Sirve con ensalada.']),
  r('huevos-plato-pisto', 'Huevos al plato con pisto', 25, 'facil', 2, ['saludable', 'verdura', 'rapida'],
    ['Huevos|4', 'Calabacín|1', 'Pimiento rojo|1', 'Cebolla|1', 'Tomate triturado|200 g', 'Aceite de oliva|1 cucharada', 'Pan integral|para acompañar'],
    ['Haz un pisto rápido: pocha la cebolla y el pimiento 8 minutos, añade el calabacín 5 minutos y el tomate 5 minutos más.', 'Reparte el pisto en 2 cazuelitas y casca 2 huevos en cada una.', 'Hornea 8–10 minutos a 200 °C, hasta que cuaje la clara.']),
  r('bowl-arroz-huevo-aguacate', 'Bowl de arroz integral, huevo, aguacate y verduras', 25, 'facil', 2, ['saludable', 'verdura'],
    ['Arroz integral|120 g', 'Huevos|2', 'Aguacate|1', 'Zanahoria|1', 'Pepino|1/2', 'Espinacas frescas|1 puñado', 'Salsa de soja|1 cucharada', 'Semillas de sésamo|1 cucharada'],
    ['Cuece el arroz integral.', 'Cuece los huevos 7 minutos (yema cremosa) y pélalos.', 'Ralla la zanahoria y corta el pepino y el aguacate.', 'Monta los boles con las espinacas, el arroz, las verduras y el huevo partido. Aliña con soja y sésamo.']),
  r('ensalada-pollo-mango', 'Ensalada de pollo, aguacate y mango', 20, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pechuga de pollo|250 g', 'Mango|1', 'Aguacate|1', 'Canónigos o lechuga|2 puñados', 'Cebolla morada|1/4', 'Lima o limón|1', 'Aceite de oliva|2 cucharadas', 'Nueces|un puñado'],
    ['Haz el pollo a la plancha y córtalo en tiras.', 'Corta el mango y el aguacate en dados y la cebolla en juliana fina.', 'Mezcla todo con las hojas y las nueces.', 'Aliña con aceite, zumo de lima y sal.']),
  r('salmorejo-huevo-atun', 'Salmorejo ligero con huevo y atún', 20, 'facil', 2, ['saludable', 'verdura', 'rapida'],
    ['Tomates maduros|700 g', 'Pan del día anterior|60 g', 'Ajo|1/2 diente', 'Aceite de oliva virgen extra|3 cucharadas', 'Vinagre|1 cucharadita', 'Huevo cocido|1', 'Atún al natural|1 lata'],
    ['Trocea los tomates y tritúralos con el pan, el ajo, el vinagre y sal.', 'Añade el aceite poco a poco mientras sigues triturando, hasta que quede cremoso.', 'Enfría en la nevera.', 'Sirve con huevo cocido picado y atún por encima.']),
  r('sopa-asiatica-pollo', 'Sopa de fideos de arroz con pollo y verduras', 30, 'facil', 2, ['saludable', 'carne'],
    ['Caldo de pollo|800 ml', 'Pechuga de pollo|200 g', 'Fideos de arroz|100 g', 'Zanahoria|1', 'Champiñones|100 g', 'Cebolleta|1', 'Jengibre fresco|un trocito', 'Salsa de soja|2 cucharadas', 'Lima o limón|1/2'],
    ['Calienta el caldo con el jengibre en láminas y la soja.', 'Añade el pollo en tiras finas, la zanahoria en bastones y los champiñones laminados. Cuece 8 minutos.', 'Añade los fideos y cuece lo que indique el paquete (3–4 minutos).', 'Sirve con la cebolleta picada y unas gotas de lima.']),
  r('musaka-ligera', 'Musaka ligera', 60, 'media', 3, ['saludable', 'carne', 'verdura'],
    ['Berenjenas|2', 'Carne picada de ternera o cordero|300 g', 'Cebolla|1', 'Tomate triturado|300 g', 'Canela|una pizca', 'Yogur griego ligero|1', 'Huevo|1', 'Queso rallado|40 g', 'Aceite de oliva|1 cucharada'],
    ['Corta las berenjenas en rodajas y hornéalas 15 minutos a 200 °C con sal.', 'Pocha la cebolla, dora la carne, añade el tomate y la canela y cocina 15 minutos.', 'Mezcla el yogur con el huevo, la mitad del queso y sal.', 'Monta capas de berenjena y carne, cubre con la mezcla de yogur y el resto del queso.', 'Hornea 25 minutos a 190 °C.']),
]
