import { r } from './build'

/** Ideas saludables (1/2): pollo, carne magra y pescado. Raciones para 2. */
export const HEALTHY_POOL_1 = [
  r('pollo-curry-basmati', 'Pollo al curry suave con arroz basmati', 35, 'facil', 2, ['saludable', 'carne'],
    ['Pechuga de pollo|300 g', 'Arroz basmati|120 g', 'Cebolla|1', 'Ajo|1 diente', 'Curry en polvo|2 cucharaditas', 'Tomate triturado|200 g', 'Yogur natural|1', 'Espinacas frescas|1 puñado', 'Aceite de oliva|1 cucharada', 'Sal|al gusto'],
    ['Cuece el arroz y resérvalo.', 'Pocha la cebolla y el ajo picados en el aceite 6 minutos.', 'Añade el pollo en dados y dóralo. Echa el curry y remueve 1 minuto.', 'Incorpora el tomate y cocina 10 minutos. Apaga, añade el yogur y las espinacas y mezcla.', 'Sirve con el arroz.']),
  r('pollo-teriyaki-brocoli', 'Pollo teriyaki casero con brócoli y arroz', 30, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Contramuslos de pollo deshuesados|400 g', 'Brócoli|1/2', 'Arroz|120 g', 'Salsa de soja|3 cucharadas', 'Miel|1 cucharada', 'Jengibre fresco|un trocito', 'Ajo|1 diente', 'Maizena|1 cucharadita', 'Semillas de sésamo|1 cucharada'],
    ['Cuece el arroz y el brócoli al vapor (5 minutos).', 'Mezcla la soja, la miel, el jengibre y el ajo rallados, la maizena y 3 cucharadas de agua.', 'Dora el pollo en trozos en una sartén sin apenas aceite 8 minutos.', 'Vierte la salsa y cocina 2 minutos hasta que espese y brille.', 'Sirve con el arroz, el brócoli y sésamo.']),
  r('fajitas-pollo', 'Fajitas de pollo con pimientos', 25, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pechuga de pollo|300 g', 'Pimiento rojo|1', 'Pimiento verde|1', 'Cebolla|1', 'Tortillas de trigo integrales|4', 'Pimentón dulce|1 cucharadita', 'Comino molido|1/2 cucharadita', 'Lima o limón|1/2', 'Yogur natural|1', 'Lechuga|unas hojas'],
    ['Corta el pollo y las verduras en tiras.', 'Saltea el pollo con pimentón, comino y sal 5 minutos. Sácalo.', 'Saltea los pimientos y la cebolla 6 minutos, que queden al dente.', 'Junta todo y riega con el zumo de lima.', 'Calienta las tortillas y rellénalas con lechuga, el salteado y una cucharada de yogur.']),
  r('pollo-limon-judias', 'Pollo al limón con judías verdes', 30, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pechuga de pollo|2 filetes', 'Judías verdes|300 g', 'Limón|1', 'Ajo|2 dientes', 'Caldo de pollo|100 ml', 'Tomillo|una pizca', 'Aceite de oliva|1 cucharada', 'Sal y pimienta|al gusto'],
    ['Cuece las judías 8 minutos en agua con sal y escúrrelas.', 'Salpimienta el pollo y dóralo 4 minutos por lado. Sácalo.', 'En la misma sartén dora el ajo laminado, añade el caldo, el zumo de limón y el tomillo.', 'Vuelve a meter el pollo y las judías y deja 3 minutos para que se impregnen de la salsa.']),
  r('brochetas-pollo-yogur', 'Brochetas de pollo marinado en yogur con ensalada', 40, 'facil', 2, ['saludable', 'carne'],
    ['Pechuga de pollo|350 g', 'Yogur natural|1', 'Pimentón dulce|1 cucharadita', 'Comino molido|1/2 cucharadita', 'Ajo|1 diente', 'Limón|1/2', 'Pimiento rojo|1', 'Cebolla|1', 'Tomate|2', 'Pepino|1'],
    ['Mezcla el yogur con las especias, el ajo rallado, el limón y sal. Marina el pollo en dados al menos 20 minutos.', 'Monta las brochetas alternando pollo, pimiento y cebolla.', 'Hazlas a la plancha o en el horno a 220 °C unos 12–15 minutos, dándoles la vuelta.', 'Sirve con una ensalada de tomate y pepino.']),
  r('pollo-cuscus-verduras', 'Pollo a la plancha con cuscús de verduras', 25, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pechuga de pollo|2 filetes', 'Cuscús|120 g', 'Calabacín|1/2', 'Zanahoria|1', 'Pimiento rojo|1/2', 'Caldo de verduras|150 ml', 'Hierbabuena o perejil|un poco', 'Aceite de oliva|1 cucharada', 'Sal|al gusto'],
    ['Pica las verduras en daditos y saltéalas 5 minutos con el aceite.', 'Añade el caldo caliente y el cuscús, apaga el fuego, tapa y deja 5 minutos. Suelta con un tenedor.', 'Haz el pollo a la plancha con sal, 4 minutos por lado.', 'Sirve el pollo cortado sobre el cuscús con la hierba picada.']),
  r('contramuslos-romero', 'Contramuslos al horno con patata y romero', 50, 'facil', 2, ['saludable', 'carne'],
    ['Contramuslos de pollo sin piel|4', 'Patatas|2', 'Cebolla|1', 'Ajo|4 dientes', 'Romero|1 rama', 'Limón|1/2', 'Aceite de oliva|2 cucharadas', 'Sal y pimienta|al gusto'],
    ['Precalienta el horno a 200 °C.', 'Corta las patatas en gajos y la cebolla en trozos. Ponlos en una bandeja con el aceite, sal y los ajos enteros.', 'Coloca encima los contramuslos salpimentados, el romero y el zumo de limón.', 'Hornea 40 minutos, dándoles la vuelta a mitad.']),
  r('cesar-ligera', 'Ensalada César ligera con pollo', 20, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Pechuga de pollo|250 g', 'Lechuga romana|1', 'Pan integral|2 rebanadas', 'Parmesano|30 g', 'Yogur natural|1', 'Mostaza|1 cucharadita', 'Limón|1/2', 'Ajo|1/2 diente', 'Aceite de oliva|1 cucharada'],
    ['Haz el pollo a la plancha y córtalo en tiras.', 'Tuesta el pan en dados en la sartén o el horno para los picatostes.', 'Para la salsa, mezcla el yogur con la mostaza, el limón, el ajo rallado, la mitad del parmesano y sal.', 'Mezcla la lechuga troceada con la salsa y pon encima el pollo, los picatostes y el resto del parmesano.']),
  r('wrap-pollo-aguacate', 'Wrap de pollo, aguacate y lechuga', 15, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Tortillas de trigo integrales|2', 'Pechuga de pollo|200 g', 'Aguacate|1', 'Tomate|1', 'Lechuga|unas hojas', 'Queso fresco batido|2 cucharadas', 'Pimentón|una pizca'],
    ['Haz el pollo a la plancha con sal y pimentón y córtalo en tiras.', 'Machaca el aguacate con un tenedor y una pizca de sal.', 'Unta las tortillas con el queso batido y el aguacate.', 'Añade lechuga, tomate en rodajas y el pollo, enrolla bien apretado y corta por la mitad.']),
  r('pollo-champis-espinacas', 'Pollo con champiñones y espinacas en salsa ligera', 30, 'facil', 2, ['saludable', 'carne'],
    ['Pechuga de pollo|300 g', 'Champiñones|200 g', 'Espinacas frescas|100 g', 'Ajo|2 dientes', 'Leche evaporada ligera o nata para cocinar ligera|150 ml', 'Mostaza|1 cucharadita', 'Aceite de oliva|1 cucharada', 'Sal y pimienta|al gusto'],
    ['Dora el pollo en dados con el aceite 5 minutos. Sácalo.', 'Saltea los champiñones laminados con el ajo 5 minutos.', 'Añade la leche evaporada y la mostaza y deja que espese 3 minutos.', 'Mete el pollo y las espinacas y cocina 2 minutos. Sirve solo o con un poco de arroz.']),
  r('pollo-pimenton-garbanzos', 'Pollo al pimentón con garbanzos', 35, 'facil', 2, ['saludable', 'carne', 'legumbres'],
    ['Contramuslos de pollo deshuesados|350 g', 'Garbanzos cocidos|1 bote (400 g)', 'Cebolla|1', 'Pimiento rojo|1', 'Ajo|2 dientes', 'Pimentón de la Vera|1 cucharadita', 'Tomate triturado|200 g', 'Aceite de oliva|1 cucharada'],
    ['Dora el pollo en trozos con sal. Sácalo.', 'Pocha la cebolla, el pimiento y el ajo picados 8 minutos.', 'Añade el pimentón, remueve y echa enseguida el tomate. Cocina 5 minutos.', 'Incorpora el pollo, los garbanzos escurridos y un vaso pequeño de agua. Cocina 15 minutos a fuego suave.']),
  r('burrito-bowl', 'Burrito bowl de pollo, arroz y alubias', 30, 'facil', 2, ['saludable', 'carne', 'legumbres'],
    ['Pechuga de pollo|250 g', 'Arroz|100 g', 'Alubias rojas cocidas|1/2 bote', 'Maíz dulce|1 lata pequeña', 'Aguacate|1', 'Tomate|1', 'Cebolla morada|1/4', 'Lima o limón|1/2', 'Pimentón y comino|1/2 cucharadita de cada', 'Lechuga|unas hojas'],
    ['Cuece el arroz y, al final, riégalo con el zumo de lima.', 'Sazona el pollo con pimentón, comino y sal, hazlo a la plancha y córtalo.', 'Pica el tomate y la cebolla como un pico de gallo.', 'Monta los boles: lechuga, arroz, alubias, maíz, pollo, aguacate y el tomate picado.']),
  r('albondigas-pollo-tomate', 'Albóndigas de pollo en salsa de tomate', 45, 'media', 3, ['saludable', 'carne'],
    ['Carne picada de pollo|400 g', 'Huevo|1', 'Copos de avena|3 cucharadas', 'Ajo|1 diente', 'Perejil fresco|un poco', 'Cebolla|1', 'Tomate triturado|400 g', 'Orégano|1 cucharadita', 'Aceite de oliva|1 cucharada'],
    ['Mezcla el pollo con el huevo, la avena, el ajo y el perejil picados y sal. Forma bolitas.', 'Hornéalas 12 minutos a 200 °C (o dóralas en la sartén con poco aceite).', 'Pocha la cebolla en el aceite, añade el tomate y el orégano y cocina 10 minutos.', 'Mete las albóndigas en la salsa y cocina 10 minutos más.']),
  r('pechuga-rellena-espinacas', 'Pechuga rellena de espinacas y queso', 40, 'media', 2, ['saludable', 'carne'],
    ['Pechugas de pollo enteras|2', 'Espinacas frescas|80 g', 'Queso fresco o mozzarella ligera|80 g', 'Ajo|1 diente', 'Tomate cherry|150 g', 'Aceite de oliva|1 cucharada', 'Sal y pimienta|al gusto'],
    ['Saltea las espinacas con el ajo 2 minutos y déjalas enfriar.', 'Abre las pechugas como un libro con un corte lateral, sin llegar al final. Salpimienta.', 'Rellena con las espinacas y el queso, y cierra con palillos.', 'Dóralas en una sartén 2 minutos por lado y termina 18 minutos en el horno a 190 °C con los tomates cherry.']),
  r('pollo-mostaza-miel', 'Pollo a la mostaza y miel con zanahorias asadas', 40, 'facil', 2, ['saludable', 'carne'],
    ['Pechuga o contramuslos de pollo|400 g', 'Zanahorias|4', 'Mostaza de Dijon|2 cucharadas', 'Miel|1 cucharada', 'Limón|1/2', 'Tomillo|una pizca', 'Aceite de oliva|1 cucharada', 'Sal|al gusto'],
    ['Precalienta el horno a 200 °C.', 'Corta las zanahorias en bastones y hornéalas 10 minutos con el aceite y sal.', 'Mezcla la mostaza, la miel, el limón y el tomillo, y pinta el pollo con la mezcla.', 'Pon el pollo en la bandeja y hornea todo 25 minutos.']),
  r('pollo-tandoori', 'Pollo tandoori al horno con ensalada de pepino', 40, 'facil', 2, ['saludable', 'carne'],
    ['Contramuslos de pollo sin piel|4', 'Yogur natural|2', 'Especias tandoori (o curry + pimentón)|2 cucharaditas', 'Ajo|1 diente', 'Limón|1', 'Pepino|1', 'Cebolla morada|1/2', 'Hierbabuena|unas hojas'],
    ['Mezcla 1 yogur con las especias, el ajo rallado, medio limón y sal. Marina el pollo al menos 20 minutos.', 'Hornea a 220 °C unos 25–30 minutos, hasta que se tueste por fuera.', 'Pica el pepino y la cebolla y mézclalos con el otro yogur, la hierbabuena y el resto del limón.', 'Sirve el pollo con la ensalada de pepino.']),
  r('hamburguesa-ternera-boniato', 'Hamburguesa casera con boniato al horno', 35, 'facil', 2, ['saludable', 'carne'],
    ['Carne picada de ternera magra|300 g', 'Boniato|1 grande', 'Cebolla|1/2', 'Pan de hamburguesa integral|2 (opcional)', 'Lechuga|unas hojas', 'Tomate|1', 'Pimentón|1/2 cucharadita', 'Aceite de oliva|1 cucharada', 'Sal y pimienta|al gusto'],
    ['Corta el boniato en bastones, alíñalo con el aceite, sal y pimentón y hornéalo 25 minutos a 210 °C.', 'Mezcla la carne con la cebolla muy picada, sal y pimienta. Forma 2 hamburguesas.', 'Hazlas a la plancha 3–4 minutos por lado.', 'Sirve en pan o al plato, con lechuga, tomate y el boniato.']),
  r('chili-pavo', 'Chili con carne de pavo y alubias', 45, 'facil', 3, ['saludable', 'carne', 'legumbres'],
    ['Carne picada de pavo|300 g', 'Alubias rojas cocidas|1 bote (400 g)', 'Tomate triturado|400 g', 'Cebolla|1', 'Pimiento rojo|1', 'Ajo|2 dientes', 'Comino molido|1 cucharadita', 'Pimentón|1 cucharadita', 'Cayena|una pizca (opcional)', 'Aceite de oliva|1 cucharada'],
    ['Pocha la cebolla, el pimiento y el ajo picados en el aceite 8 minutos.', 'Añade el pavo y dóralo bien.', 'Incorpora las especias, el tomate y un vaso pequeño de agua. Cocina 15 minutos.', 'Añade las alubias escurridas y cocina 10 minutos más. Sirve solo o con un poco de arroz.']),
  r('solomillo-manzana', 'Solomillo de cerdo con manzana y cebolla', 35, 'facil', 2, ['saludable', 'carne'],
    ['Solomillo de cerdo|1 (unos 400 g)', 'Manzanas|2', 'Cebolla|1', 'Tomillo|una pizca', 'Vino blanco|1/2 vaso', 'Aceite de oliva|1 cucharada', 'Sal y pimienta|al gusto'],
    ['Salpimienta el solomillo y dóralo entero en una cazuela con el aceite por todos los lados.', 'Añade la cebolla en juliana y la manzana en gajos y rehoga 5 minutos.', 'Echa el vino y el tomillo, tapa y cocina a fuego suave 15 minutos.', 'Deja reposar la carne 5 minutos, córtala en medallones y sirve con la manzana y la cebolla.']),
  r('lomo-mostaza-verduras', 'Lomo a la mostaza con verduras asadas', 35, 'facil', 2, ['saludable', 'carne'],
    ['Filetes de lomo de cerdo|4', 'Mostaza a la antigua|1 cucharada', 'Calabacín|1', 'Berenjena|1/2', 'Pimiento rojo|1', 'Cebolla|1', 'Aceite de oliva|2 cucharadas', 'Sal|al gusto'],
    ['Corta las verduras en trozos y ásalas 25 minutos a 200 °C con el aceite y sal.', 'Unta los filetes con la mostaza y sal.', 'Hazlos a la plancha 2 minutos por lado.', 'Sirve el lomo con las verduras asadas.']),
  r('ternera-brocoli', 'Ternera salteada con brócoli al estilo chino', 25, 'facil', 2, ['saludable', 'carne', 'rapida'],
    ['Filetes de ternera finos|300 g', 'Brócoli|1', 'Ajo|2 dientes', 'Jengibre fresco|un trocito', 'Salsa de soja|3 cucharadas', 'Maizena|1 cucharadita', 'Aceite de oliva|1 cucharada', 'Arroz|100 g (opcional)'],
    ['Corta la ternera en tiras finas y mézclala con 1 cucharada de soja y la maizena.', 'Escalda el brócoli en ramilletes 2 minutos.', 'Saltea la ternera a fuego muy fuerte 2 minutos. Sácala.', 'Saltea el ajo, el jengibre y el brócoli 2 minutos, vuelve a meter la carne con el resto de la soja y un chorrito de agua. Sirve con arroz si quieres.']),
  r('albondigas-ternera-horno', 'Albóndigas de ternera al horno con salsa de tomate', 45, 'facil', 3, ['saludable', 'carne'],
    ['Carne picada de ternera magra|400 g', 'Huevo|1', 'Pan rallado integral|2 cucharadas', 'Ajo|1 diente', 'Perejil fresco|un poco', 'Tomate triturado|400 g', 'Cebolla|1', 'Albahaca u orégano|al gusto', 'Aceite de oliva|1 cucharada'],
    ['Mezcla la carne con el huevo, el pan rallado, el ajo y el perejil picados y sal. Forma bolas.', 'Hornéalas 15 minutos a 200 °C.', 'Mientras, haz una salsa pochando la cebolla y cocinando el tomate con la albahaca 15 minutos.', 'Junta las albóndigas con la salsa y cocina 5 minutos.']),
  r('berenjenas-rellenas-carne', 'Berenjenas rellenas de carne picada', 50, 'media', 2, ['saludable', 'carne', 'verdura'],
    ['Berenjenas|2', 'Carne picada de ternera o pavo|250 g', 'Cebolla|1', 'Tomate triturado|200 g', 'Queso rallado ligero|50 g', 'Orégano|1 cucharadita', 'Aceite de oliva|1 cucharada', 'Sal|al gusto'],
    ['Parte las berenjenas por la mitad, haz cortes en la carne y hornéalas 25 minutos a 200 °C.', 'Vacía la pulpa con una cuchara y pícala.', 'Pocha la cebolla, añade la carne y dórala. Incorpora la pulpa, el tomate y el orégano y cocina 10 minutos.', 'Rellena las berenjenas, pon el queso y gratina 8 minutos.']),
  r('pimientos-rellenos-pavo', 'Pimientos rellenos de pavo y arroz', 55, 'media', 2, ['saludable', 'carne'],
    ['Pimientos rojos grandes|2', 'Carne picada de pavo|200 g', 'Arroz cocido|100 g', 'Cebolla|1/2', 'Tomate triturado|150 g', 'Queso rallado ligero|40 g', 'Comino|una pizca', 'Aceite de oliva|1 cucharada'],
    ['Corta la parte de arriba de los pimientos y quítales las semillas.', 'Sofríe la cebolla, añade el pavo y dóralo. Echa el tomate, el comino y sal y cocina 5 minutos.', 'Mezcla con el arroz y rellena los pimientos.', 'Pon el queso encima y hornea 35 minutos a 190 °C.']),
  r('pastel-carne-coliflor', 'Pastel de carne con puré de coliflor', 50, 'media', 3, ['saludable', 'carne', 'verdura'],
    ['Carne picada de ternera|350 g', 'Coliflor|1 pequeña', 'Zanahoria|1', 'Cebolla|1', 'Guisantes|100 g', 'Tomate triturado|150 g', 'Queso rallado|40 g', 'Aceite de oliva|1 cucharada', 'Sal y pimienta|al gusto'],
    ['Cuece la coliflor 15 minutos, escúrrela bien y tritúrala con sal y pimienta hasta hacer un puré.', 'Sofríe la cebolla y la zanahoria picadas, añade la carne y dórala. Incorpora el tomate y los guisantes y cocina 10 minutos.', 'Pon la carne en una fuente, cubre con el puré y espolvorea el queso.', 'Hornea 15 minutos a 200 °C hasta que se dore.']),
  r('salmon-teriyaki', 'Salmón teriyaki con arroz y pepino', 25, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Lomos de salmón|2', 'Arroz|120 g', 'Pepino|1', 'Salsa de soja|3 cucharadas', 'Miel|1 cucharada', 'Jengibre fresco|un trocito', 'Semillas de sésamo|1 cucharada', 'Vinagre de arroz o de manzana|1 cucharada'],
    ['Cuece el arroz.', 'Corta el pepino en rodajas finas y alíñalo con el vinagre y una pizca de sal.', 'Mezcla la soja, la miel y el jengibre rallado.', 'Dora el salmón 3 minutos por la piel y 2 por el otro lado. Añade la salsa y deja que reduzca 1 minuto bañándolo.', 'Sirve con el arroz, el pepino y sésamo.']),
  r('merluza-papillote', 'Merluza en papillote con verduras', 25, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Lomos de merluza|2', 'Calabacín|1/2', 'Zanahoria|1', 'Puerro|1/2', 'Limón|1/2', 'Eneldo o perejil|un poco', 'Aceite de oliva|1 cucharada', 'Sal|al gusto', 'Papel de horno|1 hoja por ración'],
    ['Precalienta el horno a 200 °C.', 'Corta las verduras en tiras muy finas.', 'En cada hoja de papel pon una cama de verduras, encima la merluza con sal, limón, hierbas y un chorrito de aceite.', 'Cierra bien el paquete doblando los bordes y hornea 15 minutos.']),
  r('bacalao-pisto', 'Bacalao con pisto', 40, 'facil', 2, ['saludable', 'pescado', 'verdura'],
    ['Lomos de bacalao desalado|2', 'Calabacín|1', 'Pimiento rojo|1', 'Pimiento verde|1', 'Cebolla|1', 'Tomate triturado|300 g', 'Aceite de oliva|2 cucharadas', 'Sal|al gusto'],
    ['Pica todas las verduras en daditos.', 'Pocha la cebolla y los pimientos 10 minutos, añade el calabacín 8 minutos y el tomate 10 minutos más.', 'Coloca el bacalao encima del pisto con la piel hacia arriba.', 'Tapa y cocina 6–8 minutos a fuego suave.']),
  r('lubina-panadera', 'Lubina al horno con patata panadera ligera', 45, 'facil', 2, ['saludable', 'pescado'],
    ['Lubinas limpias (o 4 lomos)|2', 'Patatas|2', 'Cebolla|1', 'Pimiento verde|1', 'Ajo|2 dientes', 'Vino blanco|1/2 vaso', 'Aceite de oliva|2 cucharadas', 'Sal|al gusto'],
    ['Corta las patatas, la cebolla y el pimiento en rodajas finas. Hornea con sal y 1 cucharada de aceite a 200 °C 25 minutos, con un chorrito de agua para que no se sequen.', 'Sala la lubina y colócala encima.', 'Riega con el vino, el ajo laminado y el resto del aceite.', 'Hornea 15 minutos más.']),
  r('atun-plancha-ensalada', 'Atún a la plancha con ensalada de tomate y cebolla', 20, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Filetes de atún fresco|2', 'Tomates maduros|2', 'Cebolla morada|1/2', 'Aceitunas|un puñado', 'Orégano|una pizca', 'Aceite de oliva virgen extra|2 cucharadas', 'Vinagre|1 cucharada', 'Sal gruesa|al gusto'],
    ['Corta los tomates en rodajas y la cebolla en juliana fina. Aliña con aceite, vinagre, orégano y sal.', 'Seca bien el atún y hazlo en una plancha muy caliente 1–2 minutos por lado (mejor jugoso por dentro).', 'Sirve el atún con sal gruesa junto a la ensalada y las aceitunas.']),
  r('poke-salmon', 'Poke bowl de salmón', 25, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Salmón fresco (congelado previamente)|250 g', 'Arroz|120 g', 'Aguacate|1', 'Pepino|1/2', 'Zanahoria|1', 'Maíz dulce|1 lata pequeña', 'Salsa de soja|3 cucharadas', 'Semillas de sésamo|1 cucharada', 'Vinagre de arroz o de manzana|1 cucharada'],
    ['Cuece el arroz, alíñalo con el vinagre y deja que se temple.', 'Corta el salmón en dados y mézclalo con 2 cucharadas de soja. Si prefieres, márcalo 1 minuto en la sartén.', 'Corta el aguacate, el pepino y ralla la zanahoria.', 'Monta los boles con el arroz de base y el resto por encima. Termina con soja y sésamo.']),
  r('tacos-pescado', 'Tacos de pescado con col y salsa de yogur', 30, 'facil', 2, ['saludable', 'pescado'],
    ['Pescado blanco (merluza, bacalao…)|300 g', 'Tortillas de maíz o trigo pequeñas|6', 'Col o lombarda|1/4', 'Yogur natural|1', 'Lima o limón|1', 'Cilantro o perejil|un poco', 'Pimentón|1 cucharadita', 'Comino|1/2 cucharadita', 'Aceite de oliva|1 cucharada'],
    ['Corta la col muy fina y alíñala con la mitad del zumo de lima y sal.', 'Mezcla el yogur con el resto de la lima, sal y el cilantro picado.', 'Sazona el pescado con pimentón, comino y sal y hazlo a la plancha. Desmígalo.', 'Calienta las tortillas y rellénalas con col, pescado y la salsa de yogur.']),
  r('gambas-zoodles', 'Gambas al ajillo con espaguetis de calabacín', 20, 'facil', 2, ['saludable', 'pescado', 'rapida', 'verdura'],
    ['Gambas peladas|250 g', 'Calabacines|2', 'Ajo|3 dientes', 'Guindilla|1 (opcional)', 'Perejil fresco|un poco', 'Limón|1/2', 'Aceite de oliva|2 cucharadas', 'Sal|al gusto'],
    ['Corta el calabacín en tiras finas como espaguetis (con un pelador o espiralizador).', 'Dora el ajo laminado y la guindilla en el aceite. Añade las gambas y hazlas 2 minutos.', 'Incorpora el calabacín y saltea 2 minutos, que quede al dente.', 'Termina con perejil, limón y sal.']),
  r('sardinas-horno', 'Sardinas al horno con ensalada de patata', 30, 'facil', 2, ['saludable', 'pescado'],
    ['Sardinas limpias|500 g', 'Patatas|2', 'Cebolleta|1', 'Pimiento verde|1', 'Perejil fresco|un poco', 'Ajo|1 diente', 'Limón|1', 'Aceite de oliva|2 cucharadas', 'Sal gruesa|al gusto'],
    ['Cuece las patatas con piel 20 minutos, pélalas y córtalas en trozos. Aliña con cebolleta y pimiento picados, aceite y sal.', 'Coloca las sardinas en una bandeja con sal gruesa, ajo y perejil picados.', 'Hornea a 220 °C 8–10 minutos.', 'Sirve con limón y la ensalada de patata.']),
  r('merluza-tomate-pimientos', 'Merluza en salsa de tomate y pimientos', 30, 'facil', 2, ['saludable', 'pescado'],
    ['Merluza en rodajas|400 g', 'Pimiento rojo|1', 'Pimiento verde|1', 'Cebolla|1', 'Ajo|2 dientes', 'Tomate triturado|300 g', 'Aceite de oliva|1 cucharada', 'Sal|al gusto'],
    ['Pocha la cebolla, los pimientos y el ajo en tiras 10 minutos.', 'Añade el tomate y cocina 10 minutos.', 'Sala la merluza, métela en la salsa, tapa y cocina 6–8 minutos a fuego suave.']),
  r('curry-pescado-coco', 'Curry de pescado blanco con leche de coco ligera', 30, 'facil', 2, ['saludable', 'pescado'],
    ['Pescado blanco en tacos|300 g', 'Leche de coco ligera|200 ml', 'Cebolla|1', 'Ajo|1 diente', 'Jengibre fresco|un trocito', 'Curry en polvo|2 cucharaditas', 'Tomate triturado|150 g', 'Espinacas frescas|1 puñado', 'Arroz basmati|100 g', 'Lima o limón|1/2'],
    ['Cuece el arroz.', 'Pocha la cebolla, el ajo y el jengibre picados 6 minutos. Añade el curry y remueve 1 minuto.', 'Incorpora el tomate y la leche de coco y cocina 5 minutos.', 'Añade el pescado y las espinacas y cocina 5 minutos a fuego suave. Termina con lima y sirve con el arroz.']),
  r('hamburguesa-salmon', 'Hamburguesas de salmón con ensalada', 30, 'facil', 2, ['saludable', 'pescado'],
    ['Salmón sin piel|300 g', 'Cebolleta|1/2', 'Huevo|1', 'Pan rallado|2 cucharadas', 'Eneldo o perejil|un poco', 'Limón|1/2', 'Lechuga y tomate|para la ensalada', 'Aceite de oliva|1 cucharada'],
    ['Pica el salmón a cuchillo en trocitos pequeños.', 'Mézclalo con la cebolleta picada, el huevo, el pan rallado, las hierbas, la ralladura de limón y sal. Forma 2 hamburguesas.', 'Deja 10 minutos en la nevera para que se asienten.', 'Hazlas a la plancha 3 minutos por lado y sirve con ensalada.']),
  r('sepia-plancha-arroz', 'Sepia a la plancha con arroz y alioli ligero', 30, 'facil', 2, ['saludable', 'pescado'],
    ['Sepia limpia|400 g', 'Arroz|100 g', 'Ajo|2 dientes', 'Perejil fresco|un poco', 'Yogur natural|1', 'Limón|1/2', 'Aceite de oliva|2 cucharadas', 'Sal|al gusto'],
    ['Cuece el arroz.', 'Para el alioli ligero, mezcla el yogur con 1/2 diente de ajo rallado, limón, un chorrito de aceite y sal.', 'Corta la sepia en trozos y hazla en una plancha muy caliente 4–5 minutos.', 'Al final añade el resto del ajo y el perejil picados con un chorrito de aceite.', 'Sirve con el arroz y el alioli.']),
  r('salmon-costra-hierbas', 'Salmón con costra de hierbas y verduras al vapor', 30, 'facil', 2, ['saludable', 'pescado'],
    ['Lomos de salmón|2', 'Pan rallado|2 cucharadas', 'Perejil fresco|un poco', 'Ajo|1 diente', 'Mostaza|1 cucharadita', 'Brócoli|1/2', 'Zanahoria|1', 'Aceite de oliva|1 cucharada'],
    ['Mezcla el pan rallado con el perejil y el ajo picados y el aceite.', 'Unta el salmón con la mostaza y cúbrelo con la mezcla, presionando.', 'Hornea 12 minutos a 200 °C.', 'Mientras, cuece las verduras al vapor 6–7 minutos y sirve juntos.']),
  r('bacalao-garbanzos-espinacas', 'Bacalao con garbanzos y espinacas', 35, 'facil', 2, ['saludable', 'pescado', 'legumbres'],
    ['Bacalao desalado|250 g', 'Garbanzos cocidos|1 bote (400 g)', 'Espinacas frescas|150 g', 'Cebolla|1', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Tomate triturado|150 g', 'Aceite de oliva|1 cucharada'],
    ['Pocha la cebolla y el ajo picados 6 minutos.', 'Añade el pimentón, remueve y echa el tomate. Cocina 5 minutos.', 'Incorpora los garbanzos escurridos, las espinacas y un vaso pequeño de agua.', 'Añade el bacalao en trozos y cocina 6 minutos a fuego suave.']),
  r('ensalada-arroz-atun', 'Ensalada de arroz con atún y maíz', 25, 'facil', 2, ['saludable', 'pescado', 'rapida'],
    ['Arroz|120 g', 'Atún al natural|2 latas', 'Maíz dulce|1 lata pequeña', 'Pimiento rojo|1/2', 'Pepino|1/2', 'Huevos|2', 'Aceitunas|un puñado', 'Aceite de oliva|2 cucharadas', 'Vinagre|1 cucharada'],
    ['Cuece el arroz y los huevos (10 minutos). Enfría el arroz bajo el grifo.', 'Pica el pimiento y el pepino.', 'Mezcla el arroz con el atún, el maíz, las verduras y las aceitunas.', 'Aliña y pon el huevo picado por encima.']),
]
