import { r } from './build'

/** Ideas para el menú familiar: cocina casera española. Raciones para 4. */
export const FAMILY_POOL = [
  r('arroz-al-horno', 'Arroz al horno', 75, 'media', 4, ['carne', 'legumbres'],
    ['Arroz redondo|320 g', 'Costilla de cerdo troceada|300 g', 'Morcilla de cebolla|1', 'Garbanzos cocidos|1/2 bote', 'Patata|1', 'Tomate|2', 'Ajo|1 cabeza', 'Pimentón dulce|1 cucharadita', 'Caldo de carne|750 ml', 'Aceite de oliva|4 cucharadas'],
    ['Precalienta el horno a 220 °C.', 'En una cazuela de barro o fuente de horno, dora la costilla con sal. Añade la patata en rodajas y dórala. Añade la morcilla en rodajas 1 minuto.', 'Añade el pimentón, el arroz y los garbanzos, y remueve.', 'Vierte el caldo hirviendo, coloca el tomate en rodajas y la cabeza de ajo en el centro.', 'Hornea 20 minutos y deja reposar 5.']),
  r('marmitako', 'Marmitako de bonito', 45, 'facil', 4, ['pescado'],
    ['Bonito o atún fresco|600 g', 'Patatas|4', 'Cebolla|1', 'Pimiento verde|1', 'Pimiento rojo|1', 'Ajo|2 dientes', 'Carne de pimiento choricero|1 cucharada', 'Tomate triturado|150 g', 'Caldo de pescado|1 litro', 'Aceite de oliva|3 cucharadas'],
    ['Pocha la cebolla, los pimientos y el ajo picados 10 minutos.', 'Añade la carne de choricero y el tomate y cocina 5 minutos.', 'Incorpora las patatas "chascadas" y rehoga 2 minutos. Cubre con el caldo y cuece 20 minutos.', 'Apaga el fuego, añade el bonito en dados con sal y tapa. Se hará en 5 minutos con el calor.']),
  r('patatas-riojana', 'Patatas a la riojana', 45, 'facil', 4, ['carne'],
    ['Patatas|1 kg', 'Chorizo|200 g', 'Cebolla|1', 'Pimiento verde|1', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Carne de pimiento choricero|1 cucharada', 'Laurel|1 hoja', 'Aceite de oliva|3 cucharadas'],
    ['Pocha la cebolla, el pimiento y el ajo 8 minutos.', 'Añade el chorizo en rodajas 2 minutos, el pimentón y la carne de choricero.', 'Incorpora las patatas chascadas y el laurel, cubre con agua y sala.', 'Cuece 25 minutos a fuego medio hasta que el caldo espese.']),
  r('carne-guisada-patatas', 'Carne guisada con patatas', 90, 'media', 4, ['carne'],
    ['Carne de ternera para guisar (aguja o morcillo)|800 g', 'Patatas|4', 'Cebolla|1', 'Zanahorias|2', 'Pimiento verde|1', 'Ajo|2 dientes', 'Tomate triturado|200 g', 'Vino tinto|1 vaso', 'Laurel|1 hoja', 'Harina|1 cucharada', 'Aceite de oliva|3 cucharadas'],
    ['Enharina la carne en tacos con sal y dórala en la olla. Sácala.', 'Pocha la cebolla, el pimiento, la zanahoria y el ajo 10 minutos. Añade el tomate 5 minutos.', 'Vuelve a meter la carne, echa el vino y deja evaporar. Cubre con agua, añade el laurel y cuece 1 hora tapado (20 minutos en olla exprés).', 'Añade las patatas en trozos y cuece 20 minutos más.']),
  r('sopa-castellana', 'Sopa castellana (sopa de ajo)', 30, 'facil', 4, [],
    ['Pan del día anterior|200 g', 'Ajo|6 dientes', 'Jamón serrano en taquitos|100 g', 'Pimentón dulce|1 cucharada', 'Caldo de pollo o agua|1,5 litros', 'Huevos|4', 'Aceite de oliva|4 cucharadas'],
    ['Dora los ajos laminados en el aceite. Añade el jamón y el pan en rebanadas finas y tuesta un poco.', 'Aparta del fuego, añade el pimentón y remueve.', 'Vierte el caldo caliente y cuece 15 minutos.', 'Casca los huevos en la sopa, deja que cuajen 3 minutos y sirve.']),
  r('gazpacho', 'Gazpacho andaluz', 20, 'facil', 4, ['verdura', 'rapida'],
    ['Tomates maduros|1 kg', 'Pimiento verde|1', 'Pepino|1/2', 'Ajo|1 diente', 'Pan del día anterior|50 g', 'Aceite de oliva virgen extra|80 ml', 'Vinagre de Jerez|2 cucharadas', 'Sal|al gusto', 'Agua fría|200 ml'],
    ['Trocea los tomates, el pimiento, el pepino y el ajo.', 'Tritúralos con el pan, el vinagre y la sal.', 'Añade el aceite poco a poco mientras sigues triturando y después el agua.', 'Cuela si quieres y enfría bien en la nevera.']),
  r('crema-verduras', 'Crema de verduras', 35, 'facil', 4, ['verdura'],
    ['Puerro|2', 'Zanahorias|3', 'Calabacín|1', 'Patata|1', 'Cebolla|1', 'Caldo de verduras|1 litro', 'Quesitos|2', 'Aceite de oliva|2 cucharadas'],
    ['Pocha la cebolla y el puerro 8 minutos.', 'Añade el resto de verduras en trozos y el caldo. Cuece 20 minutos.', 'Tritura con los quesitos y ajusta de sal.']),
  r('arroz-cubana', 'Arroz a la cubana', 30, 'facil', 4, ['rapida'],
    ['Arroz|320 g', 'Huevos|4', 'Plátanos|2', 'Tomate frito|400 g', 'Ajo|1 diente', 'Aceite de oliva|para freír'],
    ['Dora el ajo en una cucharada de aceite, añade el arroz, rehoga 1 minuto y cuécelo en el doble de agua con sal 18 minutos.', 'Calienta el tomate frito.', 'Fríe los plátanos partidos a lo largo y los huevos.', 'Sirve el arroz en forma de flan con el tomate, el huevo y el plátano.']),
  r('canelones-carne', 'Canelones de carne', 75, 'media', 4, ['carne'],
    ['Placas de canelones|16', 'Carne picada mixta|400 g', 'Cebolla|1', 'Tomate triturado|200 g', 'Leche|700 ml', 'Harina|60 g', 'Mantequilla|50 g', 'Queso rallado|80 g', 'Nuez moscada|una pizca', 'Aceite de oliva|2 cucharadas'],
    ['Hidrata las placas según el paquete.', 'Pocha la cebolla, dora la carne, añade el tomate y cocina 15 minutos.', 'Para la bechamel, derrite la mantequilla, tuesta la harina 2 minutos y añade la leche poco a poco sin dejar de remover. Sal y nuez moscada.', 'Mezcla la carne con 3 cucharadas de bechamel, rellena y enrolla los canelones.', 'Cubre con bechamel y queso y gratina 15 minutos a 200 °C.']),
  r('lasana-carne', 'Lasaña de carne', 80, 'media', 4, ['carne'],
    ['Placas de lasaña|12', 'Carne picada mixta|500 g', 'Cebolla|1', 'Zanahoria|1', 'Tomate triturado|400 g', 'Leche|700 ml', 'Harina|60 g', 'Mantequilla|50 g', 'Queso rallado|100 g', 'Orégano|1 cucharadita'],
    ['Haz la boloñesa: pocha la cebolla y la zanahoria, dora la carne, añade el tomate y el orégano y cocina 20 minutos.', 'Haz una bechamel con la mantequilla, la harina y la leche.', 'Monta capas: bechamel, placas, carne. Repite 3 veces y termina con placas, bechamel y queso.', 'Hornea 30 minutos a 190 °C.']),
  r('croquetas-jamon', 'Croquetas de jamón', 90, 'dificil', 4, ['carne'],
    ['Jamón serrano|150 g', 'Cebolla|1/2', 'Mantequilla|60 g', 'Harina|90 g', 'Leche|750 ml', 'Huevos|2', 'Pan rallado|para rebozar', 'Aceite de oliva|para freír', 'Nuez moscada|una pizca'],
    ['Pocha la cebolla muy picada en la mantequilla. Añade el jamón picado 1 minuto.', 'Añade la harina y tuéstala 2 minutos. Ve echando la leche caliente sin dejar de remover 15 minutos, hasta que la masa se despegue de la sartén.', 'Pasa la masa a una fuente, tapa a piel y deja enfriar en la nevera varias horas.', 'Forma las croquetas, pásalas por huevo y pan rallado y fríelas en aceite bien caliente. Sirve con ensalada.']),
  r('empanada-atun', 'Empanada gallega de atún', 70, 'media', 4, ['pescado'],
    ['Láminas de masa de empanada|2', 'Atún en aceite|3 latas', 'Cebollas|2', 'Pimiento rojo|1', 'Pimiento verde|1', 'Tomate triturado|200 g', 'Huevos cocidos|2', 'Huevo para pintar|1', 'Aceite de oliva|3 cucharadas'],
    ['Pocha las cebollas y los pimientos en tiras 20 minutos. Añade el tomate 10 minutos.', 'Mezcla con el atún escurrido y el huevo cocido picado. Deja templar.', 'Extiende una lámina en la bandeja, reparte el relleno y cubre con la otra. Sella los bordes y haz un agujero en el centro.', 'Pinta con huevo y hornea 35 minutos a 190 °C.']),
  r('calamares-tinta', 'Calamares en su tinta con arroz blanco', 60, 'media', 4, ['pescado'],
    ['Calamares limpios|800 g', 'Cebollas|2', 'Pimiento verde|1', 'Ajo|2 dientes', 'Tomate triturado|200 g', 'Tinta de calamar|4 sobres', 'Vino blanco|1 vaso', 'Arroz|240 g', 'Aceite de oliva|4 cucharadas'],
    ['Pocha las cebollas, el pimiento y el ajo picados 15 minutos.', 'Añade los calamares en anillas y rehoga 5 minutos. Echa el vino y el tomate.', 'Disuelve la tinta en un poco de agua, añádela y cocina tapado 30 minutos a fuego suave.', 'Sirve con arroz blanco.']),
  r('merluza-romana', 'Merluza a la romana con ensalada', 25, 'facil', 4, ['pescado', 'rapida'],
    ['Merluza en rodajas o lomos|800 g', 'Harina|para rebozar', 'Huevos|2', 'Limón|1', 'Lechuga|1', 'Tomates|2', 'Aceite de oliva|para freír'],
    ['Sala el pescado.', 'Pásalo por harina y huevo batido.', 'Fríelo en aceite caliente 2–3 minutos por lado y escúrrelo en papel.', 'Sirve con limón y ensalada.']),
  r('bacalao-vizcaina', 'Bacalao a la vizcaína', 50, 'media', 4, ['pescado'],
    ['Lomos de bacalao desalado|4', 'Cebollas|3', 'Pimientos choriceros (o 2 cucharadas de su carne)|4', 'Ajo|2 dientes', 'Tomate triturado|200 g', 'Pan|1 rebanada', 'Aceite de oliva|5 cucharadas'],
    ['Si usas pimientos choriceros secos, hidrátalos en agua caliente y saca su carne.', 'Pocha las cebollas y el ajo a fuego muy suave 30 minutos con el pan.', 'Añade la carne de choricero y el tomate, cocina 10 minutos y tritura la salsa.', 'Pon el bacalao en la salsa con la piel hacia arriba y cocina 10 minutos a fuego suave.']),
  r('trucha-navarra', 'Trucha a la navarra', 25, 'facil', 4, ['pescado', 'rapida'],
    ['Truchas limpias|4', 'Jamón serrano|4 lonchas', 'Harina|para rebozar', 'Ajo|2 dientes', 'Limón|1', 'Aceite de oliva|6 cucharadas', 'Patatas|4 (para acompañar)'],
    ['Sala las truchas por dentro y mete una loncha de jamón en cada una.', 'Pásalas por harina.', 'Fríelas en el aceite con los ajos 4–5 minutos por lado.', 'Sirve con limón y patatas cocidas o asadas.']),
  r('conejo-ajillo', 'Conejo al ajillo', 50, 'facil', 4, ['carne'],
    ['Conejo troceado|1', 'Ajo|1 cabeza', 'Vino blanco|1 vaso', 'Tomillo|1 cucharadita', 'Laurel|1 hoja', 'Perejil fresco|un poco', 'Aceite de oliva|5 cucharadas'],
    ['Sala el conejo y dóralo en el aceite por todos los lados.', 'Añade los ajos enteros aplastados, el tomillo y el laurel y rehoga 3 minutos.', 'Echa el vino y un poco de agua, tapa y cocina 30 minutos a fuego suave.', 'Espolvorea el perejil al servir.']),
  r('costillas-horno', 'Costillas de cerdo al horno con patatas', 90, 'facil', 4, ['carne'],
    ['Costillas de cerdo|1,2 kg', 'Patatas|4', 'Ajo|3 dientes', 'Pimentón dulce|1 cucharada', 'Orégano|1 cucharadita', 'Vino blanco|1 vaso', 'Miel|1 cucharada', 'Aceite de oliva|3 cucharadas'],
    ['Mezcla el aceite con el ajo picado, el pimentón, el orégano, la miel y sal. Unta las costillas.', 'Ponlas en una bandeja con las patatas en gajos y el vino.', 'Tapa con papel de aluminio y hornea 45 minutos a 180 °C.', 'Destapa, sube a 210 °C y hornea 25 minutos más hasta que se doren.']),
  r('carrillada-vino', 'Carrilleras al vino tinto con puré', 150, 'media', 4, ['carne'],
    ['Carrilleras de cerdo|8', 'Cebollas|2', 'Zanahorias|2', 'Ajo|2 dientes', 'Vino tinto|1/2 litro', 'Caldo de carne|300 ml', 'Harina|2 cucharadas', 'Patatas|4 (para el puré)', 'Leche|100 ml', 'Aceite de oliva|3 cucharadas'],
    ['Enharina las carrilleras con sal y dóralas. Sácalas.', 'Pocha las cebollas, las zanahorias y el ajo 15 minutos.', 'Mete la carne, echa el vino y el caldo y cocina tapado 2 horas a fuego suave (45 minutos en olla exprés).', 'Tritura la salsa. Sirve con puré de patata hecho con la leche y un poco de aceite.']),
  r('filetes-ternera-salsa', 'Filetes de ternera en salsa con champiñones', 45, 'facil', 4, ['carne'],
    ['Filetes de ternera|8', 'Champiñones|250 g', 'Cebolla|1', 'Ajo|2 dientes', 'Vino blanco|1 vaso', 'Caldo de carne|1 vaso', 'Harina|para rebozar', 'Aceite de oliva|4 cucharadas'],
    ['Sala y enharina los filetes y dóralos por los dos lados. Sácalos.', 'Pocha la cebolla y el ajo. Añade los champiñones laminados 5 minutos.', 'Echa el vino, deja evaporar y añade el caldo.', 'Mete los filetes y cocina 20 minutos a fuego suave. Sirve con patatas o arroz.']),
  r('flamenquines', 'Flamenquines caseros', 40, 'media', 4, ['carne'],
    ['Filetes de lomo de cerdo finos|8', 'Jamón serrano|8 lonchas', 'Queso en lonchas|4 (opcional)', 'Huevos|2', 'Harina|para rebozar', 'Pan rallado|para rebozar', 'Aceite de oliva|para freír', 'Ensalada|para acompañar'],
    ['Aplana los filetes. Pon encima jamón (y queso) y enróllalos bien apretados.', 'Pásalos por harina, huevo y pan rallado.', 'Fríelos en aceite caliente hasta que estén dorados, unos 5 minutos.', 'Sirve con ensalada o patatas.']),
  r('huevos-flamenca', 'Huevos a la flamenca', 40, 'facil', 4, ['verdura'],
    ['Huevos|8', 'Tomate triturado|400 g', 'Cebolla|1', 'Pimiento rojo|1', 'Guisantes|150 g', 'Chorizo|100 g', 'Jamón serrano|4 lonchas', 'Espárragos blancos|1 lata pequeña', 'Aceite de oliva|2 cucharadas'],
    ['Pocha la cebolla y el pimiento, añade el chorizo en rodajas y el tomate y cocina 15 minutos. Añade los guisantes.', 'Reparte la salsa en cazuelitas y casca 2 huevos en cada una.', 'Decora con el jamón y los espárragos.', 'Hornea 10 minutos a 200 °C, hasta que cuaje la clara.']),
  r('sopa-fideos-pollo', 'Sopa de fideos con pollo', 60, 'facil', 4, ['carne'],
    ['Muslos de pollo|2', 'Zanahorias|2', 'Puerro|1', 'Apio|1 rama', 'Fideos finos|150 g', 'Hueso de jamón|1', 'Sal|al gusto'],
    ['Pon el pollo, el hueso y las verduras en una olla con 2 litros de agua. Cuece 45 minutos quitando la espuma.', 'Cuela el caldo y desmiga el pollo.', 'Cuece los fideos en el caldo 4 minutos.', 'Añade el pollo desmigado y sirve.']),
  r('alubias-pintas', 'Alubias pintas con chorizo', 120, 'facil', 4, ['legumbres'],
    ['Alubias pintas|400 g', 'Chorizo|1', 'Morcilla|1', 'Panceta|100 g', 'Cebolla|1', 'Pimiento verde|1', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Aceite de oliva|3 cucharadas'],
    ['La noche anterior pon las alubias en remojo.', 'Pon las alubias con agua fría, la cebolla, el pimiento, el ajo y la panceta. Cuando hierva, baja el fuego.', 'Añade el chorizo y la morcilla y cuece 1 hora y media a fuego muy suave, "asustando" con agua fría 2 o 3 veces.', 'Tritura las verduras y devuélvelas al guiso. Sofríe el pimentón en un poco de aceite y añádelo. Sala.']),
  r('judias-almejas', 'Judías blancas con almejas', 40, 'media', 4, ['legumbres', 'pescado'],
    ['Alubias blancas cocidas|2 botes (800 g)', 'Almejas|400 g', 'Cebolla|1', 'Ajo|2 dientes', 'Pimiento verde|1', 'Vino blanco|1/2 vaso', 'Caldo de pescado|400 ml', 'Perejil fresco|un poco', 'Aceite de oliva|3 cucharadas'],
    ['Deja las almejas en agua con sal 30 minutos.', 'Pocha la cebolla, el pimiento y el ajo 10 minutos.', 'Añade el vino, deja evaporar y echa el caldo y las alubias enjuagadas. Cuece 10 minutos.', 'Añade las almejas y el perejil, tapa y cocina 3 minutos hasta que se abran.']),
  r('potaje-vigilia', 'Potaje de vigilia (garbanzos con bacalao y espinacas)', 60, 'media', 4, ['legumbres', 'pescado'],
    ['Garbanzos|300 g (o 2 botes cocidos)', 'Bacalao desalado|300 g', 'Espinacas|300 g', 'Cebolla|1', 'Ajo|3 dientes', 'Pimentón dulce|1 cucharadita', 'Huevos cocidos|2', 'Pan frito|1 rebanada', 'Aceite de oliva|3 cucharadas'],
    ['Si son secos, cuece los garbanzos remojados la noche anterior (o usa de bote).', 'Pocha la cebolla, añade el pimentón y un majado de ajo con el pan frito.', 'Añade los garbanzos con su caldo y las espinacas y cuece 10 minutos.', 'Añade el bacalao en trozos 5 minutos. Sirve con huevo cocido picado.']),
  r('menestra', 'Menestra de verduras con jamón', 45, 'media', 4, ['verdura'],
    ['Judías verdes|200 g', 'Alcachofas|4 (o de bote)', 'Guisantes|150 g', 'Zanahorias|2', 'Coliflor|1/4', 'Patata|1', 'Jamón serrano en taquitos|100 g', 'Cebolla|1', 'Ajo|2 dientes', 'Harina|1 cucharada', 'Aceite de oliva|3 cucharadas'],
    ['Cuece cada verdura por separado en agua con sal hasta que esté tierna. Guarda un poco del agua.', 'Pocha la cebolla y el ajo y añade el jamón.', 'Añade la harina, remueve y echa un vaso del agua de cocción.', 'Incorpora todas las verduras y cocina 5 minutos.']),
  r('patatas-costillas', 'Patatas guisadas con costillas', 60, 'facil', 4, ['carne'],
    ['Costilla de cerdo troceada|600 g', 'Patatas|1 kg', 'Cebolla|1', 'Pimiento verde|1', 'Tomate|1', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Laurel|1 hoja', 'Aceite de oliva|3 cucharadas'],
    ['Dora las costillas con sal.', 'Añade la cebolla, el pimiento y el ajo picados y pocha 8 minutos. Añade el tomate rallado.', 'Echa el pimentón, las patatas chascadas y el laurel. Cubre con agua.', 'Cuece 35 minutos a fuego medio.']),
  r('arroz-caldoso-pollo', 'Arroz caldoso de pollo y verduras', 50, 'media', 4, ['carne'],
    ['Arroz redondo|320 g', 'Pollo troceado|1/2', 'Pimiento rojo|1', 'Judías verdes|150 g', 'Tomate|2', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Azafrán o colorante|una pizca', 'Caldo de pollo|1,8 litros', 'Aceite de oliva|4 cucharadas'],
    ['Dora el pollo con sal en una cazuela. Añade el pimiento y las judías y rehoga 5 minutos.', 'Añade el ajo y el tomate rallado y sofríe 5 minutos. Echa el pimentón.', 'Vierte el caldo con el azafrán y cuece 10 minutos.', 'Añade el arroz y cuece 17 minutos. Debe quedar meloso y con caldo. Sirve enseguida.']),
  r('fideua', 'Fideuá', 45, 'media', 4, ['pescado'],
    ['Fideos gruesos de fideuá|400 g', 'Gambas|300 g', 'Calamar o sepia|300 g', 'Tomate|2', 'Ajo|2 dientes', 'Pimentón dulce|1 cucharadita', 'Caldo de pescado|1 litro', 'Azafrán o colorante|una pizca', 'Aceite de oliva|4 cucharadas', 'Alioli|para acompañar'],
    ['Marca las gambas en la paellera y sácalas.', 'Dora el calamar en trozos, añade el ajo y el tomate rallado y sofríe 5 minutos.', 'Añade los fideos y tuéstalos 2 minutos. Echa el pimentón, el caldo caliente y el azafrán.', 'Cuece 10 minutos a fuego medio. Pon las gambas encima al final y deja reposar. Sirve con alioli.']),
  r('pollo-asado-patatas', 'Pollo asado con patatas y cebolla', 75, 'facil', 4, ['carne'],
    ['Pollo entero|1 (1,5 kg)', 'Patatas|4', 'Cebollas|2', 'Limón|1', 'Ajo|4 dientes', 'Tomillo y romero|al gusto', 'Vino blanco|1 vaso', 'Aceite de oliva|3 cucharadas'],
    ['Precalienta el horno a 190 °C.', 'Frota el pollo con aceite, sal y las hierbas y mete dentro el limón partido y los ajos.', 'Colócalo sobre una cama de patatas y cebolla en rodajas con sal y el vino.', 'Hornea 1 hora aproximadamente, regándolo con su jugo de vez en cuando.']),
  r('filetes-rusos', 'Filetes rusos con tomate', 40, 'facil', 4, ['carne'],
    ['Carne picada mixta|600 g', 'Huevo|1', 'Ajo|1 diente', 'Perejil fresco|un poco', 'Pan rallado|para rebozar', 'Tomate frito|400 g', 'Aceite de oliva|para freír'],
    ['Mezcla la carne con el huevo, el ajo y el perejil picados y sal.', 'Forma filetes gruesos y pásalos por pan rallado.', 'Fríelos 3–4 minutos por lado.', 'Sirve con tomate frito caliente y patatas o arroz.']),
  r('escalope-milanesa', 'Escalope a la milanesa con ensalada', 30, 'facil', 4, ['carne', 'rapida'],
    ['Filetes de ternera o cerdo finos|8', 'Huevos|2', 'Pan rallado|para rebozar', 'Queso rallado|2 cucharadas', 'Perejil|un poco', 'Limón|1', 'Lechuga y tomate|para la ensalada', 'Aceite de oliva|para freír'],
    ['Sala los filetes.', 'Mezcla el pan rallado con el queso y el perejil picado.', 'Pasa los filetes por huevo y por el pan rallado.', 'Fríelos 2 minutos por lado. Sirve con limón y ensalada.']),
  r('pimientos-rellenos-carne', 'Pimientos rellenos de carne', 70, 'media', 4, ['carne'],
    ['Pimientos rojos|4', 'Carne picada mixta|400 g', 'Arroz|80 g', 'Cebolla|1', 'Tomate triturado|300 g', 'Ajo|1 diente', 'Aceite de oliva|3 cucharadas'],
    ['Cuece el arroz 10 minutos y escúrrelo.', 'Pocha la cebolla y el ajo, dora la carne y añade la mitad del tomate. Mezcla con el arroz.', 'Rellena los pimientos vaciados y tápalos con su "sombrero".', 'Ponlos en una fuente con el resto del tomate y un poco de agua y hornea 45 minutos a 180 °C.']),
  r('calabacines-gratinados', 'Calabacines rellenos gratinados', 50, 'facil', 4, ['verdura', 'carne'],
    ['Calabacines|4', 'Carne picada|300 g', 'Cebolla|1', 'Tomate frito|200 g', 'Bechamel|200 ml', 'Queso rallado|80 g', 'Aceite de oliva|2 cucharadas'],
    ['Parte los calabacines a lo largo, vacíalos y pica la pulpa.', 'Pocha la cebolla, añade la pulpa y la carne y dora. Añade el tomate frito.', 'Rellena los calabacines, cubre con bechamel y queso.', 'Hornea 30 minutos a 190 °C.']),
  r('pollo-pepitoria', 'Pollo en pepitoria', 60, 'media', 4, ['carne'],
    ['Pollo troceado|1', 'Cebolla|1', 'Ajo|3 dientes', 'Almendras crudas|50 g', 'Huevos cocidos|2', 'Azafrán|unas hebras', 'Vino blanco|1 vaso', 'Caldo de pollo|300 ml', 'Harina|para rebozar', 'Aceite de oliva|4 cucharadas'],
    ['Enharina el pollo con sal y dóralo. Sácalo.', 'En el mismo aceite fríe los ajos y las almendras y resérvalos. Pocha la cebolla picada.', 'Vuelve a meter el pollo, echa el vino y el caldo con el azafrán y cocina 30 minutos.', 'Maja los ajos, las almendras y las yemas cocidas con un poco de caldo y añádelo a la salsa. Cocina 5 minutos y sirve con la clara picada.']),
  r('lomo-horno-patatas', 'Cinta de lomo al horno con patatas', 70, 'facil', 4, ['carne'],
    ['Cinta de lomo de cerdo entera|1 kg', 'Patatas|4', 'Cebollas|2', 'Ajo|4 dientes', 'Vino blanco|1 vaso', 'Tomillo|1 cucharadita', 'Aceite de oliva|3 cucharadas'],
    ['Frota el lomo con sal, tomillo y aceite y dóralo en una sartén por todos los lados.', 'Pon en una fuente las patatas y la cebolla en rodajas con los ajos, sal y el vino. Coloca el lomo encima.', 'Hornea 50 minutos a 180 °C.', 'Deja reposar 10 minutos y corta en rodajas.']),
  r('boquerones-fritos', 'Boquerones fritos con ensalada', 25, 'facil', 4, ['pescado', 'rapida'],
    ['Boquerones limpios|800 g', 'Harina de freír|para rebozar', 'Limón|1', 'Lechuga|1', 'Tomates|2', 'Cebolla|1/2', 'Aceite de oliva|para freír'],
    ['Sala los boquerones y enharínalos, sacudiendo el exceso.', 'Fríelos en tandas en aceite muy caliente 1–2 minutos.', 'Escúrrelos en papel.', 'Sirve con limón y una ensalada.']),
  r('ensaladilla-rusa', 'Ensaladilla rusa', 40, 'facil', 4, ['pescado'],
    ['Patatas|4', 'Zanahorias|2', 'Guisantes|100 g', 'Huevos|3', 'Atún en aceite|2 latas', 'Aceitunas|un puñado', 'Pimiento asado|1', 'Mayonesa|200 g'],
    ['Cuece las patatas y las zanahorias con piel 25 minutos, y los guisantes 5 minutos. Cuece los huevos 10 minutos.', 'Pela y corta todo en daditos.', 'Mezcla con el atún, las aceitunas y la mayonesa.', 'Decora con el pimiento y el huevo, y enfría en la nevera.']),
  r('garbanzos-langostinos', 'Garbanzos con langostinos', 35, 'facil', 4, ['legumbres', 'pescado'],
    ['Garbanzos cocidos|2 botes (800 g)', 'Langostinos|400 g', 'Cebolla|1', 'Pimiento rojo|1', 'Ajo|2 dientes', 'Tomate triturado|200 g', 'Pimentón dulce|1 cucharadita', 'Caldo de pescado|400 ml', 'Aceite de oliva|3 cucharadas'],
    ['Pela los langostinos y cuece las cáscaras en el caldo 10 minutos. Cuela.', 'Pocha la cebolla, el pimiento y el ajo 10 minutos. Añade el pimentón y el tomate.', 'Añade los garbanzos y el caldo y cocina 10 minutos.', 'Añade los langostinos 2 minutos y sirve.']),
]
